updating workflows [skip ci]

diff --git a/.github/workflows/00-01-caching.yml b/.github/workflows/00-01-caching.yml
--- a/.github/workflows/00-01-caching.yml
+++ b/.github/workflows/00-01-caching.yml
@@ -1,5 +1,5 @@
 ---
-name: Cache Dependencies
+name: "Cache Dependencies"
 
 on:
   repository_dispatch:
@@ -12,64 +12,62 @@ env:
   NEXT_WORKFLOW: StyleCop Linter
 
 jobs:
-
   cache-dependencies:
     name: Cache Dependencies
     runs-on: ubuntu-latest
     timeout-minutes: 15
 
     steps:
+      - name: Checkout SHA Repository
+        uses: actions/checkout@v3.6.0
+        with:
+          ref: ${{ env.SHA }}
+          fetch-depth: 0
 
-    - name: Checkout SHA Repository
-      uses: actions/checkout@v3.6.0
-      with:
-        ref: ${{ env.SHA }}
-        fetch-depth: 0
+      - name: Restore dotnet Dependencies
+        run: |
+          echo "##[info] Restoring .NET dependencies for ${{ env.CSPROJ }}"
+          dotnet restore --no-cache "${{ env.CSPROJ }}" -v detailed || (echo "##[error] Dotnet restore failed for ${{ env.CSPROJ }}" && exit 34)
 
-    - name: Restore dotnet Dependencies
-      run: |
-        echo "##[info] Restoring .NET dependencies for ${{ env.CSPROJ }}"
-        dotnet restore --no-cache "${{ env.CSPROJ }}" -v detailed || (echo "##[error] Dotnet restore failed for ${{ env.CSPROJ }}" && exit 34)
+      - name: Cache dotnet Dependencies
+        uses: actions/cache@v3.3.1
+        with:
+          path: ~/.nuget/packages
+          key: ${{ runner.os }}-dotnet-${{ hashFiles('${{ env.SHA }}') }}
+          restore-keys: |
+            ${{ runner.os }}-dotnet-
 
-    - name: Cache dotnet Dependencies
-      uses: actions/cache@v3.3.1
-      with:
-        path: ~/.nuget/packages
-        key: ${{ runner.os }}-dotnet-${{ hashFiles('${{ env.SHA }}') }}
-        restore-keys: |
-          ${{ runner.os }}-dotnet-
+      - name: Trigger Next Workflow
+        if: success()
+        run: |
 
-    - name: Trigger Next Workflow
-      if: success()
-      run: |
-      
-        CMD=$(echo "curl -L -X POST" \
-        "-H \"Accept: application/vnd.github+json\"" \
-        "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-        "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
-        "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-        "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
-        "\"client_payload\":{" \
-        "\"sha\":\"${{ env.SHA }}\"," \
-        "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
-        "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+          CMD=$(echo "curl -L -X POST" \
+          "-H \"Accept: application/vnd.github+json\"" \
+          "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+          "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+          "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
+          "\"client_payload\":{" \
+          "\"sha\":\"${{ env.SHA }}\"," \
+          "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
+          "\"csproj\":\"${{ env.CSPROJ }}\"}'")
 
-        retries=0
-        while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-            eval "$CMD"
-            CURL_EXIT_CODE=$?
-            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-                echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
-                retries=$((retries+1))
-                if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
-                    echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-                    sleep ${{ vars.WAIT_SECONDS }}
-                else
-                    echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                    echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
-                fi
-            else
-                break # successful curl
-            fi    
-        done
-        echo "##[debug] CURL command: $CMD"
+          retries=0
+          while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+              eval "$CMD"
+              CURL_EXIT_CODE=$?
+              if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                  echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                  retries=$((retries+1))
+                  if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                      echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                      sleep ${{ vars.WAIT_SECONDS }}
+                  else
+                      echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                      echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
+                  fi
+              else
+                  break # successful curl
+              fi    
+          done
+          echo "##[debug] CURL command: $CMD"
diff --git a/.github/workflows/01-00-stylecop-linter.yml b/.github/workflows/01-00-stylecop-linter.yml
--- a/.github/workflows/01-00-stylecop-linter.yml
+++ b/.github/workflows/01-00-stylecop-linter.yml
@@ -11,88 +11,85 @@ env:
   CSPROJ: ${{ github.event.client_payload.csproj }}
 
 jobs:
-
   stylecop-linter:
-
     name: StyleCop Linter
     runs-on: ubuntu-latest
     timeout-minutes: 15
 
     steps:
+      - name: Checkout SHA Repository
+        id: checkout
+        uses: actions/checkout@v3.6.0
+        with:
+          ref: ${{ env.SHA }}
+          fetch-depth: 0
 
-    - name: Checkout SHA Repository
-      id: checkout
-      uses: actions/checkout@v3.6.0
-      with:
-        ref: ${{ env.SHA }}
-        fetch-depth: 0
+      - name: Setup .NET Environment
+        uses: actions/setup-dotnet@v3.2.0
+        with:
+          dotnet-version: "7.0.x"
 
-    - name: Setup .NET Environment
-      uses: actions/setup-dotnet@v3.2.0
-      with:
-        dotnet-version: '7.0.x'
+      - name: Retrieve Cached dotnet Dependencies
+        id: cache-dotnet-restore
+        uses: actions/cache/restore@v3
+        with:
+          path: ~/.nuget/packages
+          key: ${{ runner.os }}-dotnet-${{ env.SHA }}
+          restore-keys: ${{ runner.os }}-dotnet-
 
-    - name: Retrieve Cached dotnet Dependencies
-      id: cache-dotnet-restore
-      uses: actions/cache/restore@v3
-      with:
-        path: ~/.nuget/packages
-        key: ${{ runner.os }}-dotnet-${{ env.SHA }}
-        restore-keys: ${{ runner.os }}-dotnet-
+      - name: Restore Dependencies
+        if: steps.cache-dotnet-restore.outputs.cache-hit != 'true'
+        run: dotnet restore --no-cache "${{ env.CSPROJ }}" -v detailed || (echo "##[error] Dotnet restore failed" && exit 34)
 
-    - name: Restore Dependencies
-      if: steps.cache-dotnet-restore.outputs.cache-hit != 'true'
-      run: dotnet restore --no-cache "${{ env.CSPROJ }}" -v detailed || (echo "##[error] Dotnet restore failed" && exit 34)
+      - name: Dotnet Build with StyleCop
+        run: |
+          CMD="dotnet build --no-restore \"${{ env.CSPROJ }}\" "
+          CMD+="-v detailed "
+          CMD+="/p:StyleCopEnabled=true "
+          CMD+="/p:StyleCopTreatErrorsAsWarnings=false "
+          CMD+="/p:StyleCopForceFullAnalysis=false"
+          eval "$CMD" || (echo "##[error] Dotnet build failed" && exit 35)
 
-    - name: Dotnet Build with StyleCop
-      run: |
-        CMD="dotnet build --no-restore \"${{ env.CSPROJ }}\" "
-        CMD+="-v detailed "
-        CMD+="/p:StyleCopEnabled=true "
-        CMD+="/p:StyleCopTreatErrorsAsWarnings=false "
-        CMD+="/p:StyleCopForceFullAnalysis=false"
-        eval "$CMD" || (echo "##[error] Dotnet build failed" && exit 35)
+      - name: Trigger Next Workflow # Development-Tests | Staging-Tests | Production-Tests
+        if: success()
+        run: |
 
-    - name: Trigger Next Workflow # Development-Tests | Staging-Tests | Production-Tests
-      if: success()
-      run: |
-  
-        case "${{ env.SHA_BRANCH }}" in
-          "code-development") trigger="Development Tests" ;;
-          "code-staging") trigger="Staging Tests" ;;
-          "code-production") trigger="Production Tests" ;;
-          "main") trigger="Production Tests" ;;
-        esac
-        echo "##[info] Calling $trigger"
+          case "${{ env.SHA_BRANCH }}" in
+            "code-development") trigger="Development Tests" ;;
+            "code-staging") trigger="Staging Tests" ;;
+            "code-production") trigger="Production Tests" ;;
+            "main") trigger="Production Tests" ;;
+          esac
+          echo "##[info] Calling $trigger"
 
-        CMD=$(echo "curl -L -X POST" \
-        "-H \"Accept: application/vnd.github+json\"" \
-        "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-        "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
-        "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-        "-d '{\"event_type\":\"$trigger\"," \
-        "\"client_payload\":{" \
-        "\"sha\":\"${{ env.SHA }}\"," \
-        "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
-        "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+          CMD=$(echo "curl -L -X POST" \
+          "-H \"Accept: application/vnd.github+json\"" \
+          "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+          "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+          "-d '{\"event_type\":\"$trigger\"," \
+          "\"client_payload\":{" \
+          "\"sha\":\"${{ env.SHA }}\"," \
+          "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
+          "\"csproj\":\"${{ env.CSPROJ }}\"}'")
 
-        retries=0
-        while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-          eval "$CMD"
-          CURL_EXIT_CODE=$?
-          if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-            echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
-            retries=$((retries+1))
-            if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
-              echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-              sleep ${{ vars.WAIT_SECONDS }}
+          retries=0
+          while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+            eval "$CMD"
+            CURL_EXIT_CODE=$?
+            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+              echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+              retries=$((retries+1))
+              if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                sleep ${{ vars.WAIT_SECONDS }}
+              else
+                echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                echo "##[error] Failed to trigger $trigger workflow with CURL command: $CMD." && exit 90
+              fi
             else
-              echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-              echo "##[error] Failed to trigger $trigger workflow with CURL command: $CMD." && exit 90
+              echo "##[debug] Successful curl"
+              break
             fi
-          else
-            echo "##[debug] Successful curl"
-            break
-          fi    
-        done
-        echo "##[debug] CURL command: $CMD"
+          done
+          echo "##[debug] CURL command: $CMD"
diff --git a/.github/workflows/03-00-development-tests.yml b/.github/workflows/03-00-development-tests.yml
--- a/.github/workflows/03-00-development-tests.yml
+++ b/.github/workflows/03-00-development-tests.yml
@@ -12,7 +12,6 @@ env:
   NEXT_WORKFLOW: Versioning
 
 jobs:
-
   development-tests:
     name: Unit Tests (${{ matrix.test_framework }})
     runs-on: ubuntu-latest
@@ -23,41 +22,40 @@ jobs:
         test_framework: [Nunit, Xunit]
 
     steps:
+      - name: Checkout SHA Repository
+        id: checkout-sha
+        uses: actions/checkout@v3.6.0
+        with:
+          ref: ${{ env.SHA }}
+          fetch-depth: 0
 
-    - name: Checkout SHA Repository
-      id: checkout-sha
-      uses: actions/checkout@v3.6.0
-      with:
-        ref: ${{ env.SHA }}
-        fetch-depth: 0
+      - name: Install Test Suite Dependencies
+        run: |
 
-    - name: Install Test Suite Dependencies
-      run: |
-      
-        if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
-          test_type="Nunit_Player_Unit_Tests"
-        else
-          test_type="Xunit_Game_Unit_Tests"
-        fi
-        CMD="dotnet restore --no-cache"
-        CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
-        eval "$CMD"
+          if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
+            test_type="Nunit_Player_Unit_Tests"
+          else
+            test_type="Xunit_Game_Unit_Tests"
+          fi
+          CMD="dotnet restore --no-cache"
+          CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
+          eval "$CMD"
 
-    - name: Run Nunit and Xunit Unit Tests
-      run: |
-      
-        if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
-          test_type="Nunit_Player_Unit_Tests"
-          log_file_name="nunit-results.trx"
-        else
-          test_type="Xunit_Game_Unit_Tests"
-          log_file_name="xunit-results.trx"
-        fi
-        CMD="dotnet test"
-        CMD+=" --no-restore --verbosity detailed"
-        CMD+=" --logger \"trx;LogFileName=${log_file_name}\""
-        CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
-        eval "$CMD"
+      - name: Run Nunit and Xunit Unit Tests
+        run: |
+
+          if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
+            test_type="Nunit_Player_Unit_Tests"
+            log_file_name="nunit-results.trx"
+          else
+            test_type="Xunit_Game_Unit_Tests"
+            log_file_name="xunit-results.trx"
+          fi
+          CMD="dotnet test"
+          CMD+=" --no-restore --verbosity detailed"
+          CMD+=" --logger \"trx;LogFileName=${log_file_name}\""
+          CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
+          eval "$CMD"
 
   trigger-next-workflow:
     runs-on: ubuntu-latest
@@ -65,38 +63,37 @@ jobs:
     needs: development-tests
 
     steps:
+      - name: Trigger Next Workflow
+        if: success()
+        run: |
 
-    - name: Trigger Next Workflow
-      if: success()
-      run: |
-      
-        CMD=$(echo "curl -L -X POST" \
-        "-H \"Accept: application/vnd.github+json\"" \
-        "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-        "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
-        "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-        "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
-        "\"client_payload\":{" \
-        "\"sha\":\"${{ env.SHA }}\"," \
-        "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
-        "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+          CMD=$(echo "curl -L -X POST" \
+          "-H \"Accept: application/vnd.github+json\"" \
+          "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+          "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+          "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
+          "\"client_payload\":{" \
+          "\"sha\":\"${{ env.SHA }}\"," \
+          "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
+          "\"csproj\":\"${{ env.CSPROJ }}\"}'")
 
-        retries=0
-        while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-            eval "$CMD"
-            CURL_EXIT_CODE=$?
-            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-                echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
-                retries=$((retries+1))
-                if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
-                    echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-                    sleep ${{ vars.WAIT_SECONDS }}
-                else
-                    echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                    echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
-                fi
-            else
-                break # successful curl
-            fi    
-        done
-        echo "##[debug] CURL command: $CMD"
+          retries=0
+          while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+              eval "$CMD"
+              CURL_EXIT_CODE=$?
+              if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                  echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                  retries=$((retries+1))
+                  if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                      echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                      sleep ${{ vars.WAIT_SECONDS }}
+                  else
+                      echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                      echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
+                  fi
+              else
+                  break # successful curl
+              fi
+          done
+          echo "##[debug] CURL command: $CMD"
diff --git a/.github/workflows/04-02-deploy-docker.yml b/.github/workflows/04-02-deploy-docker.yml
--- a/.github/workflows/04-02-deploy-docker.yml
+++ b/.github/workflows/04-02-deploy-docker.yml
@@ -12,94 +12,92 @@ env:
   NEXT_WORKFLOW: Deploy Git
 
 jobs:
-
   save-docker-image:
     runs-on: ubuntu-latest
     timeout-minutes: 15
 
     steps:
-    
-    - name: Checkout SHA repository
-      uses: actions/checkout@v3.6.0
-      with:
-        ref: ${{ env.SHA }}
-        fetch-depth: 0
+      - name: Checkout SHA repository
+        uses: actions/checkout@v3.6.0
+        with:
+          ref: ${{ env.SHA }}
+          fetch-depth: 0
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2.2.0
-      with:
-        username: ${{ secrets.DOCKER_HUB_USERNAME }}
-        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2.2.0
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
 
-    - name: Enable Docker Experimental Features
-      run: |
-      
-        echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
-        sudo systemctl restart docker
-        docker version
+      - name: Enable Docker Experimental Features
+        run: |
 
-    - name: Determine next version tag
-      run: |
-      
-        git fetch --tags
-        if [ -z "$(git tag)" ]; then
-            echo "##[error] No tags found for ${{ github.repository }}" && 47
-        fi
-        latest_tag=$(git tag | sort -V | tail -n 1)     
-        echo "##[info] Latest Tag = $latest_tag"
-        echo "NEW_VERSION=${latest_tag}" >> $GITHUB_ENV
+          echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
+          sudo systemctl restart docker
+          docker version
 
-    - name: Build and Push Docker image
-      run: |
-      
-        docker_repo=$(echo "$(basename "${{ github.workspace }}")" | tr 'A-Z' 'a-z')
-        if docker manifest inspect ${{ secrets.DOCKER_HUB_USERNAME }}/$docker_repo:${{ env.NEW_VERSION }} > /dev/null; then
-            echo "Docker image already exists! Skipping Docker push."
-        else
-            docker_file=$(find ./$(echo "${{ env.SHA_BRANCH }}" | sed 's/^code-//') -name "Dockerfile" | head -n 1)
-            if [[ ! -f "$docker_file" ]]; then
-                echo "##[error] Dockerfile not found for ${{ env.SHA }} --> Exit 48"
-                exit 48
-            fi
-            CMD="docker build -t \"${{ secrets.DOCKER_HUB_USERNAME }}/$docker_repo:${{ env.NEW_VERSION }}\" "
-            CMD+="-f \"${docker_file}\" \"${{ github.workspace }}\" "
-            echo "##[info] Docker build command is $CMD"
-            eval ${CMD} || (echo "##[error] Docker build failed" && exit 49)
-            CMD="docker push \"${{ secrets.DOCKER_HUB_USERNAME }}/$docker_repo:${{ env.NEW_VERSION }}\""
-            eval ${CMD} || (echo "##[error] Docker push failed" && exit 50)
-        fi
+      - name: Determine next version tag
+        run: |
 
-    - name: Trigger Next Workflow
-      if: success()
-      run: |
-      
-        CMD=$(echo "curl -L -X POST" \
-        "-H \"Accept: application/vnd.github+json\"" \
-        "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-        "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
-        "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-        "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
-        "\"client_payload\":{" \
-        "\"sha\":\"${{ env.SHA }}\"," \
-        "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
-        "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+          git fetch --tags
+          if [ -z "$(git tag)" ]; then
+              echo "##[error] No tags found for ${{ github.repository }}" && 47
+          fi
+          latest_tag=$(git tag | sort -V | tail -n 1)
+          echo "##[info] Latest Tag = $latest_tag"
+          echo "NEW_VERSION=${latest_tag}" >> $GITHUB_ENV
 
-        retries=0
-        while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-            eval "$CMD"
-            CURL_EXIT_CODE=$?
-            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-                echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
-                retries=$((retries+1))
-                if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
-                    echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-                    sleep ${{ vars.WAIT_SECONDS }}
-                else
-                    echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                    echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
-                fi
-            else
-                break # successful curl
-            fi    
-        done
-        echo "##[debug] CURL command: $CMD"
+      - name: Build and Push Docker image
+        run: |
+
+          docker_repo=$(echo "$(basename "${{ github.workspace }}")" | tr 'A-Z' 'a-z')
+          if docker manifest inspect ${{ secrets.DOCKER_HUB_USERNAME }}/$docker_repo:${{ env.NEW_VERSION }} > /dev/null; then
+              echo "Docker image already exists! Skipping Docker push."
+          else
+              docker_file=$(find ./$(echo "${{ env.SHA_BRANCH }}" | sed 's/^code-//') -name "Dockerfile" | head -n 1)
+              if [[ ! -f "$docker_file" ]]; then
+                  echo "##[error] Dockerfile not found for ${{ env.SHA }} --> Exit 48"
+                  exit 48
+              fi
+              CMD="docker build -t \"${{ secrets.DOCKER_HUB_USERNAME }}/$docker_repo:${{ env.NEW_VERSION }}\" "
+              CMD+="-f \"${docker_file}\" \"${{ github.workspace }}\" "
+              echo "##[info] Docker build command is $CMD"
+              eval ${CMD} || (echo "##[error] Docker build failed" && exit 49)
+              CMD="docker push \"${{ secrets.DOCKER_HUB_USERNAME }}/$docker_repo:${{ env.NEW_VERSION }}\""
+              eval ${CMD} || (echo "##[error] Docker push failed" && exit 50)
+          fi
+
+      - name: Trigger Next Workflow
+        if: success()
+        run: |
+
+          CMD=$(echo "curl -L -X POST" \
+          "-H \"Accept: application/vnd.github+json\"" \
+          "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+          "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+          "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
+          "\"client_payload\":{" \
+          "\"sha\":\"${{ env.SHA }}\"," \
+          "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
+          "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+
+          retries=0
+          while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+              eval "$CMD"
+              CURL_EXIT_CODE=$?
+              if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                  echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                  retries=$((retries+1))
+                  if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                      echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                      sleep ${{ vars.WAIT_SECONDS }}
+                  else
+                      echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                      echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
+                  fi
+              else
+                  break # successful curl
+              fi
+          done
+          echo "##[debug] CURL command: $CMD"
diff --git a/.github/workflows/04-03-deploy-git.yml b/.github/workflows/04-03-deploy-git.yml
--- a/.github/workflows/04-03-deploy-git.yml
+++ b/.github/workflows/04-03-deploy-git.yml
@@ -13,176 +13,174 @@ env:
   NEXT_WORKFLOW: Deployment Success
 
 jobs:
-
   deploy-git-branches:
     runs-on: ubuntu-latest
     timeout-minutes: 15
 
     steps:
+      - name: Checkout SHA Repository
+        uses: actions/checkout@v3.6.0
+        with:
+          ref: ${{ env.SHA }}
+          fetch-depth: 0
 
-    - name: Checkout SHA Repository
-      uses: actions/checkout@v3.6.0
-      with:
-        ref: ${{ env.SHA }}
-        fetch-depth: 0
+      - name: Configure Git User
+        run: |
 
-    - name: Configure Git User
-      run: |
-      
-        git config user.name "${{ github.repository_owner}}"
-        git config user.email "${{ vars.EMAIL }}"
-        if [ $? -ne 0 ]; then
-          echo "##[error] Failed to configure Git user." && exit 40
-        fi
-        echo "##[debug] Git user configured successfully."
-
-    - name: Reset Lock File holding Commit SHA
-      run: |
-      
-        echo "##[debug] Beginning reset of lock file holding commit SHA."
-        declare -A branch_lock_map
-        branch_lock_map["code-production"]=".production.lock"
-        branch_lock_map["code-staging"]=".staging.lock"
-        branch_lock_map["code-development"]=".development.lock"
-        branch_lock_map["main"]=".main.lock"
-        lock_file=${branch_lock_map[${{ env.SHA_BRANCH }}]}
-        git fetch --all
-        git pull origin ${{ env.SHA_BRANCH }}
-        if [ $? -ne 0 ]; then
-          echo "##[error] Failed to pull from repository." && exit 41
-        fi
-        echo "##[debug] lockfile $lock_file contents: $(cat .development.lock)"
-        newer_commits=5
-        commits_to_check=$(git log -n ${newer_commits} --format="%H")
-        echo "##[debug] Commits to check: $commits_to_check"
-        commit_with_lockfile=""        
-        for commit in $commits_to_check; do
-          if git show "$commit:$lock_file" 2>/dev/null | grep -q "${{ env.SHA }}"; then
-            commit_with_lockfile=$commit
-            break
+          git config user.name "${{ github.repository_owner}}"
+          git config user.email "${{ vars.EMAIL }}"
+          if [ $? -ne 0 ]; then
+            echo "##[error] Failed to configure Git user." && exit 40
           fi
-        done
-        if [ -z "$commit_with_lockfile" ]; then
-          echo "##[error] Lock file with correct SHA not found in the next 5 commits!" && exit 42
-        fi
-        echo "##[debug] Reverting the commit that added the lock file."
-        git revert $commit_with_lockfile --no-edit
-        if [ $? -ne 0 ]; then
-          echo "##[error] Failed to revert the lockfile $lock_file commit $commit_with_lockfile" && exit 43
-        fi
-        echo "##[info] Successfully reverted lockfile."
-        
-    - name: Set Deployment Environments
-      run: |
-      
-        deploy_branches=()
-        directory=""
-        
-        case "${{ env.SHA_BRANCH }}" in
-          "code-development")
-            deploy_branches=("code-staging" "code-production")
-            directory="development"
-            ;;
-          "code-staging")
-            deploy_branches=("code-development" "code-production")
-            directory="staging"
-            ;;
-          "code-production")
-            deploy_branches=("code-development" "code-staging")
-            directory="production"
-            ;;
-           "main")
-            deploy_branches=("code-development" "code-staging" "code-production")
-            directory="production"
-            ;;
-        esac
+          echo "##[debug] Git user configured successfully."
 
-        echo "deploy_branches=${deploy_branches[@]}" >> $GITHUB_ENV
-        echo "DIRECTORY=$directory" >> $GITHUB_ENV
+      - name: Reset Lock File holding Commit SHA
+        run: |
 
-    - name: Reset all branches to mirror main if push is to main
-      run: |
-      
-        if [[ "${{ env.SHA_BRANCH }}" == "main" ]]; then
-            for target_branch in code-development code-staging code-production; do
-                git fetch origin
-                git checkout $target_branch
-                git reset --hard ${{ env.SHA }}
-                git push origin $target_branch --force
-            done
-        fi
+          echo "##[debug] Beginning reset of lock file holding commit SHA."
+          declare -A branch_lock_map
+          branch_lock_map["code-production"]=".production.lock"
+          branch_lock_map["code-staging"]=".staging.lock"
+          branch_lock_map["code-development"]=".development.lock"
+          branch_lock_map["main"]=".main.lock"
+          lock_file=${branch_lock_map[${{ env.SHA_BRANCH }}]}
+          git fetch --all
+          git pull origin ${{ env.SHA_BRANCH }}
+          if [ $? -ne 0 ]; then
+            echo "##[error] Failed to pull from repository." && exit 41
+          fi
+          echo "##[debug] lockfile $lock_file contents: $(cat .development.lock)"
+          newer_commits=5
+          commits_to_check=$(git log -n ${newer_commits} --format="%H")
+          echo "##[debug] Commits to check: $commits_to_check"
+          commit_with_lockfile=""
+          for commit in $commits_to_check; do
+            if git show "$commit:$lock_file" 2>/dev/null | grep -q "${{ env.SHA }}"; then
+              commit_with_lockfile=$commit
+              break
+            fi
+          done
+          if [ -z "$commit_with_lockfile" ]; then
+            echo "##[error] Lock file with correct SHA not found in the next 5 commits!" && exit 42
+          fi
+          echo "##[debug] Reverting the commit that added the lock file."
+          git revert $commit_with_lockfile --no-edit
+          if [ $? -ne 0 ]; then
+            echo "##[error] Failed to revert the lockfile $lock_file commit $commit_with_lockfile" && exit 43
+          fi
+          echo "##[info] Successfully reverted lockfile."
 
-    - name: Set and Copy Source Directory to Temp Dir
-      run: |
-      
-         src_dir=${{ env.SHA_BRANCH }}
-         src_dir=${src_dir#code-}
-         dir_path=$(find ${{ github.workspace }} -type d -name "$src_dir" -print | head -n 1)
-    
-         if [[ ! -d "$dir_path" ]] || [[ ! $(ls -A "$dir_path") ]]; then
-           echo "##[error] Source directory does not exist or is empty" && exit 44
-         fi
-    
-         rsync -av --delete --exclude=.git/ $dir_path/ /tmp/temp-dir/
+      - name: Set Deployment Environments
+        run: |
 
-    - name: Deploy to Target Branches
-      run: |
-      
-         if [[ "${{ env.SHA_BRANCH }}" != "main" ]]; then
-             echo "##[info] Deploying commit ${{ env.SHA }} to target branches."
-             latest_tag=$(git tag -l 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1) # v1.2.3 SemVer
-             TAG_MESSAGE=$(git tag -l --format='%(contents)' $latest_tag)
-             echo "##[info] Latest Tag = $TAG_MESSAGE"
-        
-             for target_branch in code-development code-staging code-production; do
-                 [[ $target_branch == "${{ env.SHA_BRANCH }}" ]] && continue
-                 
-                 git fetch origin
-                 git checkout $target_branch
-                 rsync -av --delete --exclude=.git/ /tmp/temp-dir/ ${{ github.workspace }}/${{ env.DIRECTORY }}/
-                 
-                 if git add -A; then
-                     COMMIT_MSG="Migrating changes from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag: $TAG_MESSAGE [skip ci]"
-                     echo "##[debug] $COMMIT_MSG"
-                     git commit -m "$COMMIT_MSG"
-                     git push origin $target_branch
-                 else
-                     echo "##[error] No changes detected. Skipping commit for $target_branch [skip ci]"
-                 fi  
-             done
-         fi
+          deploy_branches=()
+          directory=""
 
-    - name: Trigger Next Workflow
-      if: success()
-      run: |
-      
-        CMD=$(echo "curl -L -X POST" \
-          "-H \"Accept: application/vnd.github+json\"" \
-          "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-          "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
-          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-          "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
-          "\"client_payload\":{" \
-          "\"sha\":\"${{ env.SHA }}\"," \
-          "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
-          "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+          case "${{ env.SHA_BRANCH }}" in
+            "code-development")
+              deploy_branches=("code-staging" "code-production")
+              directory="development"
+              ;;
+            "code-staging")
+              deploy_branches=("code-development" "code-production")
+              directory="staging"
+              ;;
+            "code-production")
+              deploy_branches=("code-development" "code-staging")
+              directory="production"
+              ;;
+             "main")
+              deploy_branches=("code-development" "code-staging" "code-production")
+              directory="production"
+              ;;
+          esac
 
-        retries=0
-        while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-            eval "$CMD"
-            CURL_EXIT_CODE=$?
-            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-                echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
-                retries=$((retries+1))
-                if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
-                    echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-                    sleep ${{ vars.WAIT_SECONDS }}
-                else
-                    echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                    echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
-                fi
-            else
-                break # successful curl
-            fi    
-        done
-        echo "##[debug] CURL command: $CMD"
+          echo "deploy_branches=${deploy_branches[@]}" >> $GITHUB_ENV
+          echo "DIRECTORY=$directory" >> $GITHUB_ENV
+
+      - name: Reset all branches to mirror main if push is to main
+        run: |
+
+          if [[ "${{ env.SHA_BRANCH }}" == "main" ]]; then
+              for target_branch in code-development code-staging code-production; do
+                  git fetch origin
+                  git checkout $target_branch
+                  git reset --hard ${{ env.SHA }}
+                  git push origin $target_branch --force
+              done
+          fi
+
+      - name: Set and Copy Source Directory to Temp Dir
+        run: |
+
+          src_dir=${{ env.SHA_BRANCH }}
+          src_dir=${src_dir#code-}
+          dir_path=$(find ${{ github.workspace }} -type d -name "$src_dir" -print | head -n 1)
+
+          if [[ ! -d "$dir_path" ]] || [[ ! $(ls -A "$dir_path") ]]; then
+            echo "##[error] Source directory does not exist or is empty" && exit 44
+          fi
+
+          rsync -av --delete --exclude=.git/ $dir_path/ /tmp/temp-dir/
+
+      - name: Deploy to Target Branches
+        run: |
+
+          if [[ "${{ env.SHA_BRANCH }}" != "main" ]]; then
+              echo "##[info] Deploying commit ${{ env.SHA }} to target branches."
+              latest_tag=$(git tag -l 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1) # v1.2.3 SemVer
+              TAG_MESSAGE=$(git tag -l --format='%(contents)' $latest_tag)
+              echo "##[info] Latest Tag = $TAG_MESSAGE"
+
+              for target_branch in code-development code-staging code-production; do
+                  [[ $target_branch == "${{ env.SHA_BRANCH }}" ]] && continue
+
+                  git fetch origin
+                  git checkout $target_branch
+                  rsync -av --delete --exclude=.git/ /tmp/temp-dir/ ${{ github.workspace }}/${{ env.DIRECTORY }}/
+
+                  if git add -A; then
+                      COMMIT_MSG="Migrating changes from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag: $TAG_MESSAGE [skip ci]"
+                      echo "##[debug] $COMMIT_MSG"
+                      git commit -m "$COMMIT_MSG"
+                      git push origin $target_branch
+                  else
+                      echo "##[error] No changes detected. Skipping commit for $target_branch [skip ci]"
+                  fi
+              done
+          fi
+
+      - name: Trigger Next Workflow
+        if: success()
+        run: |
+
+          CMD=$(echo "curl -L -X POST" \
+            "-H \"Accept: application/vnd.github+json\"" \
+            "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+            "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+            "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
+            "\"client_payload\":{" \
+            "\"sha\":\"${{ env.SHA }}\"," \
+            "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
+            "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+
+          retries=0
+          while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+              eval "$CMD"
+              CURL_EXIT_CODE=$?
+              if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                  echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                  retries=$((retries+1))
+                  if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                      echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                      sleep ${{ vars.WAIT_SECONDS }}
+                  else
+                      echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                      echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
+                  fi
+              else
+                  break # successful curl
+              fi
+          done
+          echo "##[debug] CURL command: $CMD"
diff --git a/.github/workflows/09-00-deploy-guard.yml b/.github/workflows/09-00-deploy-guard.yml
--- a/.github/workflows/09-00-deploy-guard.yml
+++ b/.github/workflows/09-00-deploy-guard.yml
@@ -21,7 +21,6 @@ on:
       - completed
 
 jobs:
-
   revert-commit:
     name: Revert Failed Commit
     runs-on: ubuntu-latest
@@ -32,100 +31,99 @@ jobs:
     # un-comment to block execution
     #if: (github.actor != ${{ github.repository_owner }})
 
-    steps: 
+    steps:
+      - name: Extract SHA that triggered failure
+        run: |
 
-    - name: Extract SHA that triggered failure
-      run: |
-      
-        echo "##[info] Searching for .lock files in the repository."
-        lockfile_path=$(find . -name "*.lock" | head -n 1)
-        if [[ ! -z "$lockfile_path" ]]; then
-            echo "##[debug] Validating SHA1 as 40 alpha-numeric characters."
-            if [[ ${#sha} -eq 40 && $sha =~ ^[0-9a-fA-F]+$ ]]; then
-                echo "SHA=$(cat "$lockfile_path")" >> $GITHUB_ENV
-            echo "SHA=$sha" >> $GITHUB_ENV
-            else
-                echo "##[error] Content of .lock file is not a valid SHA: $sha"
-                exit 60
-            fi
-        else
-            echo "##[warn] Expected .lock file was not found."
-            exit 61
-        fi
-
-    - name: Checkout repository
-      uses: actions/checkout@v3.6.0
-      with:
-        ref: ${{ env.SHA }}
-        fetch-depth: 0
-
-    - name: Extract Branch Name from SHA Commit
-      run: |
-      
-        branch=$(git name-rev ${{ env.SHA }} | sed 's#.*/##' | sed 's#.*-##')
-        echo "BRANCH_NAME=$branch" >> $GITHUB_ENV
-
-    - name: Configure Git User
-      run: |
-      
-        git config user.name "${{ github.repository_owner}}"
-        git config user.email "${{ vars.EMAIL }}"
-
-    - name: Revert commit
-      run: |
-        git revert ${{ env.SHA }}
-        git push origin ${{ env.BRANCH_NAME }}
-
-    - name: Check and Remove Lock File with Specific SHA
-      run: |
-      
-        trap 'echo "Error on line $LINENO: $BASH_COMMAND"; exit 1' ERR
-        declare -A branch_lock_map
-        branch_lock_map["code-production"]=".production.lock"
-        branch_lock_map["code-staging"]=".staging.lock"
-        branch_lock_map["code-development"]=".development.lock"
-        branch_lock_map["main"]=".main.lock"
-
-        echo "##[debug] Branch is ${{ env.BRANCH_NAME }}"
-        lock_file=${branch_lock_map[${{ env.BRANCH_NAME }}]}
-        echo "##[debug] lock_file is $lock_file"
-
-        # Check if the lock file contains the specific SHA
-        if [[ $(cat "$lock_file") == "${{ github.event.client_payload.sha }}" ]]; then
-          echo "Removing lock file with SHA ${{ github.event.client_payload.sha }} found on branch ${{ env.BRANCH_NAME }}"
-          git rm "$lock_file"
-          if [ $? -eq 0 ]; then
-              git commit -m "Removed lock after SHA ${{ github.event.client_payload.sha }} workflow failure [skip ci]"
-              git push origin "${{ env.BRANCH_NAME }}"
+          echo "##[info] Searching for .lock files in the repository."
+          lockfile_path=$(find . -name "*.lock" | head -n 1)
+          if [[ ! -z "$lockfile_path" ]]; then
+              echo "##[debug] Validating SHA1 as 40 alpha-numeric characters."
+              if [[ ${#sha} -eq 40 && $sha =~ ^[0-9a-fA-F]+$ ]]; then
+                  echo "SHA=$(cat "$lockfile_path")" >> $GITHUB_ENV
+              echo "SHA=$sha" >> $GITHUB_ENV
+              else
+                  echo "##[error] Content of .lock file is not a valid SHA: $sha"
+                  exit 60
+              fi
           else
-              echo "Error: Failed to remove lock file"
-              exit 1
+              echo "##[warn] Expected .lock file was not found."
+              exit 61
           fi
-        else
-          echo "Lock file with SHA ${{ github.event.client_payload.sha }} not found on branch ${{ env.BRANCH_NAME }}. Exiting."
-          exit 1
-        fi
+
+      - name: Checkout repository
+        uses: actions/checkout@v3.6.0
+        with:
+          ref: ${{ env.SHA }}
+          fetch-depth: 0
+
+      - name: Extract Branch Name from SHA Commit
+        run: |
+
+          branch=$(git name-rev ${{ env.SHA }} | sed 's#.*/##' | sed 's#.*-##')
+          echo "BRANCH_NAME=$branch" >> $GITHUB_ENV
+
+      - name: Configure Git User
+        run: |
+
+          git config user.name "${{ github.repository_owner}}"
+          git config user.email "${{ vars.EMAIL }}"
+
+      - name: Revert commit
+        run: |
+          git revert ${{ env.SHA }}
+          git push origin ${{ env.BRANCH_NAME }}
+
+      - name: Check and Remove Lock File with Specific SHA
+        run: |
+
+          trap 'echo "Error on line $LINENO: $BASH_COMMAND"; exit 1' ERR
+          declare -A branch_lock_map
+          branch_lock_map["code-production"]=".production.lock"
+          branch_lock_map["code-staging"]=".staging.lock"
+          branch_lock_map["code-development"]=".development.lock"
+          branch_lock_map["main"]=".main.lock"
+
+          echo "##[debug] Branch is ${{ env.BRANCH_NAME }}"
+          lock_file=${branch_lock_map[${{ env.BRANCH_NAME }}]}
+          echo "##[debug] lock_file is $lock_file"
+
+          # Check if the lock file contains the specific SHA
+          if [[ $(cat "$lock_file") == "${{ github.event.client_payload.sha }}" ]]; then
+            echo "Removing lock file with SHA ${{ github.event.client_payload.sha }} found on branch ${{ env.BRANCH_NAME }}"
+            git rm "$lock_file"
+            if [ $? -eq 0 ]; then
+                git commit -m "Removed lock after SHA ${{ github.event.client_payload.sha }} workflow failure [skip ci]"
+                git push origin "${{ env.BRANCH_NAME }}"
+            else
+                echo "Error: Failed to remove lock file"
+                exit 1
+            fi
+          else
+            echo "Lock file with SHA ${{ github.event.client_payload.sha }} not found on branch ${{ env.BRANCH_NAME }}. Exiting."
+            exit 1
+          fi
 
   notify-committer:
     runs-on: ubuntu-latest
     needs: revert-commit
 
     steps:
-    - name: Notify committer of SHA rejection and revert branch
-      run: |
-      
-        COMMITTER=$(git log -1 --pretty=format:'%an')
-        WORKFLOW_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-        COMMENT_BODY="Hello @$COMMITTER, your recent commit ${{ github.event.workflow_run.head_sha }} "
-        COMMENT_BODY+="has failed, been reverted, and any associated lock files were removed. "
-        COMMENT_BODY+="Please check the [workflow run]($WORKFLOW_LINK) for details, "
-        COMMENT_BODY+="address any issues and try pushing again. Thank you!"
-        
-        CURL_CMD="curl -X POST"
-        CURL_CMD+=" -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\""
-        CURL_CMD+=" -H \"Accept: application/vnd.github.v3+json\""
-        CURL_CMD+=" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/comments"
-        CURL_CMD+=" -d \"{\\\"body\\\":\\\"$COMMENT_BODY\\\"}\""
-        eval "$CURL_CMD"
+      - name: Notify committer of SHA rejection and revert branch
+        run: |
+
+          COMMITTER=$(git log -1 --pretty=format:'%an')
+          WORKFLOW_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          COMMENT_BODY="Hello @$COMMITTER, your recent commit ${{ github.event.workflow_run.head_sha }} "
+          COMMENT_BODY+="has failed, been reverted, and any associated lock files were removed. "
+          COMMENT_BODY+="Please check the [workflow run]($WORKFLOW_LINK) for details, "
+          COMMENT_BODY+="address any issues and try pushing again. Thank you!"
+
+          CURL_CMD="curl -X POST"
+          CURL_CMD+=" -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\""
+          CURL_CMD+=" -H \"Accept: application/vnd.github.v3+json\""
+          CURL_CMD+=" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/comments"
+          CURL_CMD+=" -d \"{\\\"body\\\":\\\"$COMMENT_BODY\\\"}\""
+          eval "$CURL_CMD"
 
   # reset the code-dev ??? what about concurrent commits? push dev dir to main and clone main...
