Update 00-00-entry-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-entry-gate.yml b/.github/workflows/00-00-entry-gate.yml
--- a/.github/workflows/00-00-entry-gate.yml
+++ b/.github/workflows/00-00-entry-gate.yml
@@ -113,17 +113,6 @@ jobs:
         fi
         echo "##[info] Successfully validated SHA checkout for ${{ github.sha }}."
 
-    - name: Validate .csproj
-      run: |
-        echo "##[info] Validating .csproj file."
-        DIR_PATH="${{ github.workspace }}/$(echo "${{ env.SHA_BRANCH }}" | sed 's/^code-//')/${{ vars.PROJECT_NAME }}"
-        CSPROJ="${DIR_PATH}/${{ vars.PROJECT_NAME }}.csproj"
-        if [[ ! -f "$CSPROJ" ]]; then
-            echo "##[error] Failure locating .csproj file within the directory $DIR_PATH" && exit 17
-        fi
-        echo "##[info] Successfully validated dotnet .csproj file $CSPROJ."
-        echo "CSPROJ=$CSPROJ" >> $GITHUB_ENV
-
     - name: Validate SHA Branch
       run: |
         echo "##[info] Validating SHA branch."
@@ -135,6 +124,17 @@ jobs:
         fi
         echo "##[info] Successfully validated SHA branch name $branch."
         echo "SHA_BRANCH=$branch" >> $GITHUB_ENV
+
+    - name: Validate .csproj
+      run: |
+        echo "##[info] Validating .csproj file."
+        DIR_PATH="${{ github.workspace }}/$(echo "${{ env.SHA_BRANCH }}" | sed 's/^code-//')/${{ vars.PROJECT_NAME }}"
+        CSPROJ="${DIR_PATH}/${{ vars.PROJECT_NAME }}.csproj"
+        if [[ ! -f "$CSPROJ" ]]; then
+            echo "##[error] Failure locating .csproj file within the directory $DIR_PATH" && exit 17
+        fi
+        echo "##[info] Successfully validated dotnet .csproj file $CSPROJ."
+        echo "CSPROJ=$CSPROJ" >> $GITHUB_ENV
 
     - name: Validate Committer
       run: |
