Update 00-00-auth-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-auth-gate.yml b/.github/workflows/00-00-auth-gate.yml
--- a/.github/workflows/00-00-auth-gate.yml
+++ b/.github/workflows/00-00-auth-gate.yml
@@ -149,16 +149,32 @@ jobs:
             exit 30
         fi
 
-    - name: Update Gist with SHA # Step 9
+    - name: Set Gist with SHA # Step 9
       run: |
  
+        # Updating the Gist
+        gist_id="$${{ vars.SHA_GIST }}"      
         curl -L \
-          -X POST \
+          -X PATCH \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: token ${{ secrets.AUTH }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/gists/auth-gate-sha \
+          https://api.github.com/gists/$gist_id \
           -d '{"files": {"auth-gate.sha": {"content": "${{ github.sha }}"}}}'
+        
+        # Checking Gist update
+        content=$(curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: token ${{ secrets.AUTH }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/gists/$gist_id | jq '.files["auth-gate.sha"].content' -r)
+        
+        if [ "$content" == "${{ github.sha }}" ]; then
+          echo "Gist updated successfully."
+        else
+          echo "Failed to update Gist."
+          exit 1
+        fi
 
     - name: Trigger Next Workflow and Dispatch Success Event # Step 10
       if: success()
