Update 00-01-caching.yml[skip ci]

diff --git a/.github/workflows/00-01-caching.yml b/.github/workflows/00-01-caching.yml
--- a/.github/workflows/00-01-caching.yml
+++ b/.github/workflows/00-01-caching.yml
@@ -40,7 +40,7 @@ jobs:
       - name: Trigger Next Workflow
         if: success()
         run: |
-
+  
           CMD=$(echo "curl -L -X POST" \
           "-H \"Accept: application/vnd.github+json\"" \
           "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
@@ -54,20 +54,21 @@ jobs:
 
           retries=0
           while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-              eval "$CMD"
-              CURL_EXIT_CODE=$?
-              if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-                  echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
-                  retries=$((retries+1))
-                  if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
-                      echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-                      sleep ${{ vars.WAIT_SECONDS }}
-                  else
-                      echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                      echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
-                  fi
+            eval "$CMD"
+            CURL_EXIT_CODE=$?
+            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+              echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                retries=$((retries+1))
+                if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                  echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                  sleep ${{ vars.WAIT_SECONDS }}
+                else
+                  echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                  echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
+                fi
               else
-                  break # successful curl
+                echo "##[info] Curl success."
+                break
               fi    
           done
           echo "##[debug] CURL command: $CMD"
