Update 00-00-auth-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-auth-gate.yml b/.github/workflows/00-00-auth-gate.yml
--- a/.github/workflows/00-00-auth-gate.yml
+++ b/.github/workflows/00-00-auth-gate.yml
@@ -218,31 +218,29 @@ jobs:
         echo "##[debug][gist-lock] Checking for the existence of SHA gist content."  
         retries=0
 
-        # Initialize content to a non-empty value
-        content="init"
-
-        # Retry until SHA Gist is empty or max retries
-        while [[ "$content" != "" && $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+        # Retry until SHA Gist is empty, null, or max retries
+        while :; do
             # Fetch the content of SHA Gist
             content=$(curl -L \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: token ${{ secrets.AUTH }}" \
               https://api.github.com/gists/${{ vars.SHA_GIST }} | jq '.files["auth-gate.sha"].content' -r)
               
-            if [[ "$content" != "" ]]; then
+            if [[ "$content" == "" || "$content" == "null" ]]; then
+                break
+            else
                 echo "##[warn][gist-lock] SHA gist has content. Waiting and retrying..."
                 echo "##[warn][gist-lock] Blocked by SHA $content"
                 #sleep $((${{ vars.WAIT_MINUTES }} * 60))
                 sleep ${{ vars.SECONDS }}
                 retries=$((retries+1))
             fi
+            
+            if [[ $retries -ge ${{ vars.MAX_RETRIES }} ]]; then
+                echo "##[error][gist-lock] SHA gist still has content after ${{ vars.MAX_RETRIES }} retries."
+                exit 31
+            fi
         done
-
-        # If after retries Gist is still not empty, exit with error
-        if [[ "$content" != "" ]]; then
-          echo "##[error][gist-lock] SHA gist still has content after ${{ vars.MAX_RETRIES }} retries."
-          exit 31
-        fi
 
     - name: Set SHA Gist as Locked # Step 9
       run: |
