Update 00-00-auth-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-auth-gate.yml b/.github/workflows/00-00-auth-gate.yml
--- a/.github/workflows/00-00-auth-gate.yml
+++ b/.github/workflows/00-00-auth-gate.yml
@@ -35,6 +35,8 @@
 # 29 - Failed to fetch the branch.
 # 30 - Lock file found in commit.
 # 31 - Failed to trigger the next workflow.
+# 32 - All retries exhausted. Failed to update Gist.
+# 33 - Gist content mismatch.
 
 ######################################
 
@@ -65,8 +67,8 @@ jobs:
         regex_pattern="^([a-z0-9](-?[a-z0-9]){0,19})$"
         username=$(echo ${{ github.event.head_commit.author.name }} | tr '[:upper:]' '[:lower:]')
         if ! [[ "$username" =~ ${regex_pattern} ]] || [[ "$username" == -* ]]; then
-            echo "##[error][sanitise] Username contains invalid characters"
-            exit 20
+          echo "##[error][sanitise] Username contains invalid characters"
+          exit 20
         fi
 
         echo "##[debug][sanitise] Sanitising email address."
@@ -93,6 +95,66 @@ jobs:
         echo "##[warn][revert] Last commit was reverted."
         exit 0
 
+    - name: Validate Branch Names # Step 2
+      run: |
+ 
+        echo "##[info][branch] Validating branch name."
+        regex_pattern="^refs/heads/[a-zA-Z0-9_-]+$"
+        if ! [[ "${{ github.ref }}" =~ $regex_pattern ]]; then
+          echo "##[error][branch] Branch name contains invalid characters."
+          exit 21
+        fi
+
+    - name: Revert Commits if Branch Name is Unknown # Step 3
+      run: |
+ 
+        KNOWN_BRANCHES=("main" "develop" "feature" "hotfix")
+        CURRENT_BRANCH=$(echo "${{ github.ref }}" | sed -n 's#refs/heads/##p')
+        
+        if [[ ! " ${KNOWN_BRANCHES[@]} " =~ " ${CURRENT_BRANCH} " ]]; then
+          echo "##[warn][revert] Unknown branch detected. Reverting the commit."
+          
+          git config --global user.email "noreply@github.com"
+          git config --global user.name "GitHub Actions"
+          
+          git reset --hard HEAD~1
+          if [[ $? -ne 0 ]]; then
+            echo "##[error][revert] Failed to reset repository."
+            exit 22
+          fi
+          
+          git push origin +${{ github.ref }}
+          if [[ $? -ne 0 ]]; then
+            echo "##[error][revert] Failed to push the reversion."
+            exit 23
+          fi
+          
+          ISSUE_TITLE="Unknown branch detected"
+          ISSUE_BODY="An unknown branch was detected and its commit has been reverted. Branch: ${{ github.ref }}, Commit SHA: ${{ github.sha }}"
+          
+          create_issue() {
+            local title="$1"
+            local body="$2"
+            payload=$(jq -n \
+              --arg title "$title" \
+              --arg body "$body" \
+              '{title: $title, body: $body}')
+            CURL_CMD=$(echo "curl -X POST" \
+              "-H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\"" \
+              "-H \"Accept: application/vnd.github.v3+json\"" \
+              "https://api.github.com/repos/${{ github.repository }}/issues" \
+              "-d '$payload'")
+            echo "##[debug][notify] ISSUE COMMAND: $CURL_CMD"
+            eval "$CURL_CMD"
+          }
+
+          echo "##[debug][revert] Creating issue in the repository with the constructed title and body."
+          create_issue "$ISSUE_TITLE" "$ISSUE_BODY"
+
+          echo "##[warn][revert] Last commit was reverted."
+          exit 0
+        fi
+
     - name: Checkout SHA Repository # Step 4
       uses: actions/checkout@v3.6.0
       with:
@@ -103,8 +165,8 @@ jobs:
       run: |
  
         if [ $? -ne 0 ]; then
-            echo "##[error][checkout] SHA checkout failure ${{ github.sha }}"
-            exit 25
+          echo "##[error][checkout] SHA checkout failure ${{ github.sha }}"
+          exit 25
         fi
 
     - name: Check Commit Uniqueness # Step 6
@@ -117,11 +179,11 @@ jobs:
         echo "##[debug][unique] BRANCH_COUNT: $BRANCH_COUNT"
 
         if [[ $BRANCH_COUNT -eq 0 ]]; then
-            echo "##[warn][unique] No branches found containing the commit ${{ github.sha }}."
-            exit 26
+          echo "##[warn][unique] No branches found containing the commit ${{ github.sha }}."
+          exit 26
         elif [[ $BRANCH_COUNT -gt 1 ]]; then
-            echo "##[error][unique] Multiple branches contain the commit SHA ${{ github.sha }}."
-            exit 27
+          echo "##[error][unique] Multiple branches contain the commit SHA ${{ github.sha }}."
+          exit 27
         fi
 
     - name: Validate .csproj File # Step 7
@@ -131,8 +193,8 @@ jobs:
         echo "##[debug][csproj] CSPROJ_PATH: $CSPROJ_PATH"
 
         if [[ -z "$CSPROJ_PATH" ]]; then
-            echo "##[error][csproj] Failed to find the .csproj file $CSPROJ_PATH."
-            exit 28
+          echo "##[error][csproj] Failed to find the .csproj file $CSPROJ_PATH."
+          exit 28
         fi
 
     - name: Check for Pre-Existent .lock Files # Step 8
@@ -140,40 +202,45 @@ jobs:
  
         git fetch origin
         if [[ $? -ne 0 ]]; then
-            echo "##[error][lockfile] Failed to fetch the branch."
-            exit 29
+          echo "##[error][lockfile] Failed to fetch the branch."
+          exit 29
         fi
         LOCK_FILE_PATH=$(find . -name "*.lock" | head -n 1)
         if [[ -n "$LOCK_FILE_PATH" ]]; then
-            echo "##[error][lockfile] Lock file $LOCK_FILE_PATH issue."
-            exit 30
+          echo "##[error][lockfile] Lock file $LOCK_FILE_PATH issue."
+          exit 30
         fi
 
     - name: Set Gist with SHA # Step 9
       run: |
  
-        # Updating the Gist
+        echo "##[debug][gist] Updating the Gist with the current SHA."
         gist_id="${{ vars.SHA_GIST }}"      
-        curl -L \
+        CURL_CMD=$(echo "curl -L \
           -X PATCH \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: token ${{ secrets.AUTH }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
+          -H \"Accept: application/vnd.github+json\" \
+          -H \"Authorization: token ${{ secrets.AUTH }}\" \
+          -H \"X-GitHub-Api-Version: 2022-11-28\" \
           https://api.github.com/gists/$gist_id \
-          -d '{"files": {"auth-gate.sha": {"content": "${{ github.sha }}"}}}'
+          -d '{\"files\": {\"auth-gate.sha\": {\"content\": \"${{ github.sha }}\"}}}'")
+        eval "$CURL_CMD"
         
-        # Checking Gist update
+        if [[ $? -ne 0 ]]; then
+          echo "##[error][gist] Failed to update Gist with SHA."
+          exit 32
+        fi
+        
         content=$(curl -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: token ${{ secrets.AUTH }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/gists/$gist_id | jq '.files["auth-gate.sha"].content' -r)
         
-        if [ "$content" == "${{ github.sha }}" ]; then
-          echo "Gist updated successfully."
+        if [ "$content" != "${{ github.sha }}" ]; then
+          echo "##[error][gist] Gist content mismatch. Expected: ${{ github.sha }}. Got: $content."
+          exit 33
         else
-          echo "Failed to update Gist."
-          exit 1
+          echo "##[debug][gist] Gist updated successfully."
         fi
 
     - name: Trigger Next Workflow and Dispatch Success Event # Step 10
@@ -181,30 +248,30 @@ jobs:
       run: |
  
         echo "##[info][trigger] Initiating the next workflow: ${{ env.NEXT_WORKFLOW }}."
-        SUCCESS_CMD=$(echo "curl -L -X POST" \
-         "-H \"Accept: application/vnd.github+json\"" \
-         "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-         "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-         "-d '{\"event_type\":\"Authentication Gate Success\"," \
-         "\"client_payload\":{" \
-         "\"message\":\"Workflow completed successfully\"}}'")
-
+        SUCCESS_CMD=$(echo "curl -L -X POST \
+          -H \"Accept: application/vnd.github+json\" \
+          -H \"Authorization: Bearer ${{ secrets.AUTH }}\" \
+          https://api.github.com/repos/${{ github.repository }}/dispatches \
+          -d '{\"event_type\":\"Authentication Gate Success\", \
+          \"client_payload\":{ \
+          \"message\":\"Workflow completed successfully\"}}'")
         eval "$SUCCESS_CMD"
         if [[ $? -ne 0 ]]; then
           echo "##[error][trigger] Failed to send success event."
+          exit 34
         else
           echo "##[info][trigger] Success event dispatched."
         fi
 
-        CMD=$(echo "curl -L -X POST" \
-         "-H \"Accept: application/vnd.github+json\"" \
-         "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-         "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-         "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
-         "\"client_payload\":{" \
-         "\"sha\":\"${{ github.sha }}\"," \
-         "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
-         "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+        CMD=$(echo "curl -L -X POST \
+          -H \"Accept: application/vnd.github+json\" \
+          -H \"Authorization: Bearer ${{ secrets.AUTH }}\" \
+          https://api.github.com/repos/${{ github.repository }}/dispatches \
+          -d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\", \
+          \"client_payload\":{ \
+          \"sha\":\"${{ github.sha }}\", \
+          \"sha_branch\":\"${{ env.SHA_BRANCH }}\", \
+          \"csproj\":\"${{ env.CSPROJ }}\"}'")
 
         retries=0
         while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
@@ -218,7 +285,7 @@ jobs:
               sleep ${{ vars.WAIT_SECONDS }}
             else
               echo "##[error][trigger] All retries exhausted. Failed to trigger ${{ env.NEXT_WORKFLOW }}."
-              exit 31
+              exit 35
             fi
           else
             echo "##[info][trigger] ${{ env.NEXT_WORKFLOW }} successfully triggered."
