Update 00-00-entry-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-entry-gate.yml b/.github/workflows/00-00-entry-gate.yml
--- a/.github/workflows/00-00-entry-gate.yml
+++ b/.github/workflows/00-00-entry-gate.yml
@@ -80,8 +80,7 @@ jobs:
         forbidden="|\$`<>*"
         commit_msg="${{ github.event.head_commit.message }}"
         if [[ "${commit_msg}" =~ $forbidden ]]; then
-          echo "##[error] Commit message contains invalid characters. Exiting"
-          exit 12
+          echo "##[error] Commit message contains invalid characters. Exiting" && exit 12
         fi
 
         echo "##[info] Sanitisation and validation completed successfully."
