Update 00-00-entry-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-entry-gate.yml b/.github/workflows/00-00-entry-gate.yml
--- a/.github/workflows/00-00-entry-gate.yml
+++ b/.github/workflows/00-00-entry-gate.yml
@@ -85,17 +85,14 @@ jobs:
             echo "##[error] Email format is invalid" && exit 11
         fi
 
-        echo "##[debug] Commit messages cannot contain some dangerous chars, to inhibit injection of shell commands."       
-        forbidden_array=("|" "<" ">" "(" ")" "{" "}" "*" "]")
-        escaped_chars=$(printf "%s" "${forbidden_array[@]}" | tr -d ']' | sed 's/[]\\-^$/\\&/g')
-        pattern="[$escaped_chars\\]"
-        
-        echo "##[debug] Using pattern $pattern"
-        echo "##[debug] Checking if the commit_msg contains the pattern."
-        
-        if echo "$commit_msg" | grep -qE "$pattern"; then
-            echo "##[error] Commit message ${commit_msg} contains invalid characters." && exit 12
-        fi
+        echo "##[debug] Commit messages cannot contain some dangerous chars, to inhibit injection of shell commands."
+        forbidden_array=("|" "*" "[" "<" "(" "{" "]" ">" ")" "}")
+        for char in "${forbidden_array[@]}"; do
+            escaped_char=$(printf '%s' "$char" | sed 's/[][\\.*^$/]/\\&/g')
+            if echo "$1" | grep -q "$escaped_char"; then
+                echo "##[error] Commit message ${commit_msg} contains invalid character $char." && exit 12
+            fi
+        done
 
         echo "##[info] Sanitisation and validation completed successfully."
         echo "COMMIT_AUTHOR_NAME=${{ github.event.head_commit.author.name }}" >> $GITHUB_ENV
