Update 00-00-entry-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-entry-gate.yml b/.github/workflows/00-00-entry-gate.yml
--- a/.github/workflows/00-00-entry-gate.yml
+++ b/.github/workflows/00-00-entry-gate.yml
@@ -38,6 +38,7 @@ name: Authenticate User
 # 17 - Approved team is not set for the branch.
 # 18 - Committer is not authorized.
 # 19 - Another workflow from .github/workflows is still running.
+# 20 - Failure due to lock file persistence.
 # 90 - Failed to trigger next workflow.
 
 on:
@@ -61,6 +62,7 @@ jobs:
 
     - name: Sanitise and Validate Untrusted User-Controlled Details
       run: |
+      
         echo "##[info] Starting security sanitisation and validation."
 
         # Git username can start and or end with an alphanumeric character.
@@ -107,6 +109,7 @@ jobs:
 
     - name: Validate SHA
       run: |
+      
         echo "##[info] Validating SHA checkout."
         if [[ "${{ steps.checkout-sha.outcome }}" == "failure" ]]; then
             echo "##[error] SHA checkout FAIL for ${{ github.sha }}" && exit 13
@@ -115,6 +118,7 @@ jobs:
 
     - name: Validate SHA Branch
       run: |
+      
         echo "##[info] Validating SHA branch."
 
         echo "##[debug] Checking remote branches for the commit SHA"
@@ -135,6 +139,7 @@ jobs:
 
     - name: Validate .csproj
       run: |
+      
         echo "##[info] Validating .csproj file."
         DIR_PATH="${{ github.workspace }}/$(echo "${{ env.SHA_BRANCH }}" | sed 's/^code-//')/${{ vars.PROJECT_NAME }}"
         CSPROJ="${DIR_PATH}/${{ vars.PROJECT_NAME }}.csproj"
@@ -146,6 +151,7 @@ jobs:
 
     - name: Validate Committer
       run: |
+      
         echo "##[info] Authorising comitter ${{ env.COMMIT_AUTHOR_NAME }}."
         if [[ "${{ env.SHA_BRANCH }}" == "code-development" ]]; then
             APPROVED_TEAM="${{ github.repository_owner }},${{ secrets.DEVELOPMENT_TEAM }}"
@@ -167,6 +173,7 @@ jobs:
 
     - name: Report Commit Details
       run: |
+      
         echo "Reporting details of the commit, GitHub environment and runner specifics."
 
         echo "-------------------------------------------------"
@@ -221,19 +228,21 @@ jobs:
     
     - name: Check Concurrency
       run: |
+      
         echo "##[info] Requesting non-concurrent slot."
         retries=0
 
         while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-            # Make API call to check for any in-progress workflows in the repository using curl
-            response=$(curl -L \
+            echo "##[debug] Making API call to check for any in-progress workflows in the repository using curl."
+            response=$(curl -L --fail \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.AUTH }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ github.repository }}/actions/runs)
-            count=$(echo "$response" | jq '.workflow_runs | map(select(.status == "in_progress")) | length')
+              
+            count=$(echo "$response" | grep -o '"status": "in_progress"' | wc -l)
 
-            # Check if another instance is running and if so retry
+            echo "##[debug] Checking if another instance is running and if so, wait and retry."
             if [[ $count -eq 0 ]]; then
                 echo "##[info] No other workflow is running - continuing."
                 break
@@ -250,40 +259,47 @@ jobs:
 
     - name: Check for Existant Lock File
       run: |
+      
         echo "##[info] Checking for lock file."
-
+        
+        # Fetch branch list that contains the given SHA
         branch_list=$(git branch -r --contains ${{ github.sha }} | sed 's/origin\///' | xargs)
         branch=$(echo $branch_list | awk '{print $1}')
-
+        
         if [[ $branch == "code-"* ]]; then
             lock_file=${branch#code-}.lock
         elif [[ $branch == "main" ]]; then
             lock_file=.main.lock
         fi
+        
         retries=0
+        git fetch origin $branch 
+        git checkout $branch
+        
         while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-            git fetch origin $branch 
-            git checkout $branch    
             commits_before_sha=$(git rev-list ${{ github.sha }}~1..$branch  --)
+            
             if git ls-tree -r $commits_before_sha | grep "$lock_file"; then
                 retries=$((retries+1))
                 locked_sha=$(cat "$lock_file")
-                echo "##[warn] Lock file $LOCK_FILE found for commit SHA $locked_sha."
-                echo "##[warn] Waiting ${{ vars.WAIT_MINUTES }} minutes before retry $retries of ${{ vars.MAX_TRIES }}."
+                echo "##[warn] Lock file $lock_file found for commit SHA $locked_sha."
+                echo "##[warn] Waiting ${{ vars.WAIT_MINUTES }} minutes before retry $retries of ${{ vars.MAX_RETRIES }}."
                 sleep $((${{ vars.WAIT_MINUTES }} * 60))
             else
-                echo "##[info] Lock file $LOCK_FILE check passed - continuing."
+                echo "##[info] Lock file $lock_file check passed - continuing."
                 break
             fi
+            
             if [[ $retries -eq ${{ vars.MAX_RETRIES }} ]]; then
                 echo "##[error] Reached (${{ vars.MAX_RETRIES }}) max retries at ${{ vars.WAIT_MINUTES }} intervals."
-                echo "##[error] Lock file $lock_file presence presists." && exit 20
+                echo "##[error] Lock file $lock_file presence persists." && exit 20
             fi
         done
 
     - name: Trigger Next Workflow
       if: success()
       run: |
+      
         CMD="curl -L -X POST "
         CMD+="-H \"Accept: application/vnd.github+json\" "
         CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
