Update 00-00-auth-gate.yml[skip ci]

diff --git a/.github/workflows/00-00-auth-gate.yml b/.github/workflows/00-00-auth-gate.yml
--- a/.github/workflows/00-00-auth-gate.yml
+++ b/.github/workflows/00-00-auth-gate.yml
@@ -1,5 +1,5 @@
 ---
-name: Authentication Gateway
+name: Authentication Gate
 
 on:
   push:
@@ -10,8 +10,8 @@ env:
 
 jobs:
 
-  lockfile-checker:
-    name: Lockfile Checker
+  authentication-gate:
+    name: Authentication Gate
     runs-on: ubuntu-latest
     timeout-minutes: 15
     if: (github.actor != ${{ github.repository_owner }}) # ignore DevOps
@@ -101,59 +101,52 @@ jobs:
 
     - name: Check for Pre-Existent .lock File in History
       run: |
-      
-        echo "##[info] Checking for pre-existent lock file."
+  
+        echo "##[info] Checking for pre-existent lock file in the commit immediately before SHA."
+
+        echo "##[debug] Fetching branch ${{ env.SHA_BRANCH }}"
+        if ! git fetch origin ${{ env.SHA_BRANCH }}; then
+            echo "##[error] Failed to fetch ${{ env.SHA_BRANCH }}" && exit 26
+        fi
+        
+        echo "##[debug] Define the lock file based on the branch ${ env.SHA_BRANCH }}"
         branch=${{ env.SHA_BRANCH }}
         if [[ $branch == "code-"* ]]; then
-          LOCK_FILE=.${branch#code-}.lock
+            LOCK_FILE=.${branch#code-}.lock
         elif [[ $branch == "main" ]]; then
-          LOCK_FILE=.main.lock
+            LOCK_FILE=.main.lock
         fi
-    
-        retries=0
-        max_retries=${{ vars.MAX_RETRIES }}
-        wait_interval=$((${{ vars.WAIT_MINUTES }} * 60))
-    
-        while [[ $retries -lt $max_retries ]]; do
-            if ! git fetch origin ${{ env.SHA_BRANCH }}; then
-                echo "##[error] Failed to fetch ${{ env.SHA_BRANCH }}" && exit 26
-            fi
-    
-            echo "##[debug] Checking for lock file in the repository history before the SHA ${{ env.SHA }}."
-            if git log ${{ env.SHA }}^ -- $LOCK_FILE &> /dev/null; then
-                retries=$((retries+1))
-                echo "##[warn] Lock file $LOCK_FILE was found in the history before commit SHA ${{ env.SHA }}."
-                echo "##[warn] Waiting for ${{ vars.WAIT_MINUTES }} minutes before retry $retries of $max_retries."
-                sleep $wait_interval
-            else
-                echo "##[info] Lock file $LOCK_FILE does not exist in the history before commit SHA ${{ env.SHA }} - proceeding."
-                break
-            fi
-    
-            if [[ $retries -eq $max_retries ]]; then
-                echo "##[error] Reached $max_retries max retries at ${{ vars.WAIT_MINUTES }}-minute intervals."
-                echo "##[error] Lock file $LOCK_FILE presence persists in history before ${{ env.SHA }}" && exit 27
-            fi
-        done
-          
+        
+        echo "##[debug] Check the lock file's presence in the commit immediately before SHA ${{ env.SHA }}"
+        if git show ${{ env.SHA }}^:$LOCK_FILE &> /dev/null; then
+            echo "##[error] Lock file $LOCK_FILE was found in the commit immediately before SHA ${{ env.SHA }}." && exit 27
+        else
+            echo "##[info] Lock file $LOCK_FILE does not exist in the commit immediately before SHA ${{ env.SHA }} - proceeding."
+        fi
+        
+        echo "##[debug] Adding and committing the new lock file $LOCK_FILE for SHA ${{ env.SHA }}"
         echo "${{ env.SHA }}" > "${{ env.LOCK_FILE }}"
         git add "${{ env.LOCK_FILE }}"
         git commit -m "Adding ${{ env.LOCK_FILE }} for ${{ env.SHA }} [skip ci]."
-  
+        
+        echo "##[debug] Pushing the lock file."
         if ! git push origin HEAD:${{ env.SHA_BRANCH }}; then
-          echo "##[error] Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}" && exit 28
+            echo "##[error] Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}" && exit 28
         fi
-  
+        
+        echo "##[debug] Fetching again to ensure the commit went through."
         git fetch origin ${{ env.SHA_BRANCH }}
         if [ $? -ne 0 ]; then
-          echo "##[error] Failed to fetch ${{ env.SHA_BRANCH }}" && exit 29
+            echo "##[error] Failed to fetch ${{ env.SHA_BRANCH }}" && exit 29
         fi
-  
+        
+        echo "##[debug] Checking that the lock file is present in the remote."
         if ! git ls-tree HEAD -- ${{ env.LOCK_FILE }}; then
-          echo "##[error] Expected lock file ${{ env.LOCK_FILE }} was not detected remotely" && exit 30
+            echo "##[error] Expected lock file ${{ env.LOCK_FILE }} was not detected remotely" && exit 30
         fi
-  
+        
         echo "##[info] Lock file ${{ env.LOCK_FILE }} created and pushed to ${{ env.SHA_BRANCH }} for commit SHA ${{ env.SHA }}"
+
 
     - name: Trigger Next Workflow
       if: success()
