Update 00-auth-gate.yml

diff --git a/.github/workflows/00-auth-gate.yml b/.github/workflows/00-auth-gate.yml
--- a/.github/workflows/00-auth-gate.yml
+++ b/.github/workflows/00-auth-gate.yml
@@ -25,7 +25,6 @@ name: "Authentication Gateway"
 # 10 - Branch name is not recognised.
 # 11 - Approved team not set.
 # 12 - User is not authorised.
-# 25 - Curl failure due to malformed URL.
 # 90 - Concurrency failure.
 # 91 - Failed to trigger next workflow.
 #
@@ -112,21 +111,19 @@ jobs:
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ github.repository }}/actions/runs)
             count=$(echo "$response" | jq '.workflow_runs | map(select(.status == "in_progress")) | length')
-            
+
             # Check if another instance is running and if so retry
             if [[ $count -eq 0 ]]; then
                 echo "##[info] No other workflow is running - continuing."
                 break
             else
                 retries=$((retries+1))
+                if [[ $retries -eq ${{ vars.MAX_RETRIES }} ]]; then
+                    echo "##[error] Reached (${{ vars.MAX_RETRIES }}) max retries at ${{ vars.WAIT_MINUTES }} intervals."
+                    echo "##[error] Another workflow from .github/workflows is still running." && exit 90
+                fi
                 echo "##[warn] Another workflow is running. Waiting for ${{ vars.WAIT_MINUTES }} minutes before retry $retries of ${{ vars.MAX_RETRIES }}."
                 sleep $((${{ vars.WAIT_MINUTES }} * 60))
-            fi
-
-            if [[ $retries -eq ${{ vars.MAX_RETRIES }} ]]; then
-                echo "##[error] Reached (${{ vars.MAX_RETRIES }}) max retries at ${{ vars.WAIT_MINUTES }} intervals."
-                echo "##[error] Another workflow from .github/workflows is still running. --> Exit 90"
-                exit 90
             fi
         done
 
@@ -147,16 +144,11 @@ jobs:
         -H \"Accept: application/vnd.github.v3+json\" \
         -d \"${BASE}${SHA}${END}\" \
         \"https://api.github.com/repos/${{ github.repository }}/dispatches\""
-        echo "##[debug] Curl command: $CMD"
         
         retries=0
         while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
             RESPONSE_CODE=$(eval "$CMD")
             CURL_EXIT_CODE=$?
-        
-            # You no longer have a RESPONSE_CONTENT since you're only capturing the HTTP code now.
-            echo "##[debug] Response code: $RESPONSE_CODE"
-        
             if [[ $RESPONSE_CODE -ge 200 && $RESPONSE_CODE -le 299 ]]; then
                 echo "##[info] Successfully triggered workflow on attempt $((retries+1))."
                 break
@@ -164,16 +156,15 @@ jobs:
                 echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
             else
                 echo "##[warn] Attempt $((retries+1)) of ${{ vars.MAX_RETRIES }} failed with response code $RESPONSE_CODE"
-                echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-                sleep ${{ vars.WAIT_SECONDS }}
+                if [[ $((retries+1)) -lt ${{ vars.MAX_RETRIES }} ]]; then
+                    echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                    sleep ${{ vars.WAIT_SECONDS }}
+                else
+                    echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals"
+                    echo "##[error] Curl command: $CMD"
+                    echo "##[error] Completed ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} seconds"
+                    echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow." && exit 91
+                fi
             fi
             retries=$((retries+1))
         done
-        
-        # Check if all retries failed.
-        if [[ $retries -eq ${{ vars.MAX_RETRIES }} ]]; then
-            echo "##[error] Exhausted retries. Curl command: $CMD"
-            echo "##[error] Completed ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} seconds"
-            echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow --> Exit 91"
-            exit 91
-        fi
