Update 00-entry-gate.yml

diff --git a/.github/workflows/00-entry-gate.yml b/.github/workflows/00-entry-gate.yml
--- a/.github/workflows/00-entry-gate.yml
+++ b/.github/workflows/00-entry-gate.yml
@@ -114,12 +114,10 @@ jobs:
 
         # Check if committer is approved
         echo "##[info]# Committer is ${{ env.COMMIT_AUTHOR_NAME }}"
-        if ! echo "$APPROVED_TEAM" | grep -qE "(^|,) ${{ env.COMMIT_AUTHOR_NAME }}(,|$)"; then
-          echo "##[error]# Committer ${{ env.COMMIT_AUTHOR_NAME }} is not approved for branch ${{ env.SHA_BRANCH }} commit ${{ github.sha }} --> Exit 31"
-          exit 31
+        if ! echo "$APPROVED_TEAM" | grep -qE "(^|,)${{ env.COMMIT_AUTHOR_NAME }}(,|$)"; then
+            echo "##[error]# Committer ${{ env.COMMIT_AUTHOR_NAME }} is not approved for branch ${{ env.SHA_BRANCH }} commit ${{ github.sha }} --> Exit 31"
+            exit 31
         fi
-
-        exit 999999 #TODO REMOVE ME
 
     - name: Validate .csproj
       run: |
