Restructuring workflow filenames

diff --git a/.github/workflows/00-initial-commit.yml b/.github/workflows/00-initial-commit.yml
--- a/.github/workflows/00-initial-commit.yml
+++ b/.github/workflows/00-initial-commit.yml
@@ -3,18 +3,15 @@ name: "Report"
 
 # Reports on the initial SHA push
 
-# Exit Codes:
-# 1 - Error finding .csproj file
-# 2 - Failed to publish status from workflow
-# 3 - Error after successful status publication (this seems redundant, you might want to rethink this part)
-# 4 - Failed to trigger Dependency Caching Workflow
+# Exit Codes
+# 1: SHA checkout failure
+# 2: Error finding .csproj file
+# 3: Failed to publish status from workflow
+# 4: Curl command to trigger next workflow failed
 
 on:
   push:
     branches: ["code-development", "code-production", "code-staging"]
-
-env:
-  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
 
 jobs:
   report-usage:
@@ -25,34 +22,53 @@ jobs:
 
     steps:
     
-    - name: Report SHA and Workflow Timestamp
+    - name: Checkout SHA Repository
+      id: checkout-sha
+      uses: actions/checkout@v3.5.3
+      with:
+        ref: ${{ github.sha }}
+        fetch-depth: 0
+
+    - name: Handle checkout Outcome
       run: |
-        # Report the commit SHA and current timestamp
+        if [[ "${{ steps.checkout-sha.outcome }}" == "failure" ]]; then
+          echo "##[error] Failure during checkout of SHA $${{ github.sha }}."
+          exit 1
+        else
+          echo "##[debug] Successful checkout of SHA $${{ github.sha }}."
+        fi
+
+    - name: Set Commit SHA
+      run: |
         echo "SHA=${{ github.sha }}" >> $GITHUB_ENV
-        echo "${{ github.sha }}"
-        date
-
-    - name: Determine Branch Name
+        echo "##[debug] SHA=$SHA"
+ 
+    - name: Set Branch Name
       run: |
-        # Extract the branch name from the ref
-        ref=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')
-        echo "BRANCH_NAME=$ref" >> $GITHUB_ENV
+        branch=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')
+        echo "SHA_BRANCH=$branch" >> $GITHUB_ENV
+        echo "##[debug] SHA_BRANCH=$branch"
+        if git show-ref --verify --quiet refs/heads/${{ env.SHA_BRANCH }}; then
+          echo "##[debug] Branch ${{ env.SHA_BRANCH }} detected in repository ${{ github.repository }}"
+        else
+          echo "##[error] Branch ${{ env.SHA_BRANCH }} does not exist in repository ${{ github.repository }}"
+          exit 1
+        fi
 
-    - name: Determine .csproj File
+    - name: Set .csproj File
       run: |
-        CSPROJ=$(find "${{ github.workspace }}/$(echo "${{ env.BRANCH_NAME }}" | sed 's/^code-//')" -name "${{ env.PROJECT_NAME }}.csproj")
+        CSPROJ=$(find "${{ github.workspace }}/$(echo "${{ env.SHA_BRANCH }}" | sed 's/^code-//')" -name "${{ secrets.PROJECT_NAME }}.csproj")
         if [[ -z "$CSPROJ" ]]; then 
-            echo "##[error] .csproj file not found."
-            exit 1
+          echo "##[error] .csproj file not found."
+          exit 2
         fi
         echo "CSPROJ=$CSPROJ" >> $GITHUB_ENV
         echo "##[debug] CSPROJ=$CSPROJ"
 
     - name: Report Commit Details
       run: |
-        # Display various details about the commit
         echo "----- COMMIT DETAILS -----"
-        echo "Branch Name: ${{ env.BRANCH_NAME }}"
+        echo "Branch Name: ${{ env.SHA_BRANCH }}"
         echo "Commit SHA: ${{ github.sha }}"
         echo "Commit Message: ${{ github.event.head_commit.message }}"
         echo "Commit Author: ${{ github.event.head_commit.author.name }}"
@@ -63,7 +79,6 @@ jobs:
 
     - name: Report GitHub Environment and Workflow Details
       run: |
-        # Display various details about the GitHub environment and workflow
         echo "----- GITHUB ENVIRONMENT & WORKFLOW DETAILS -----"
         echo "Date: $(date)"
         echo "Event Name: ${{ github.event_name }}"
@@ -82,7 +97,6 @@ jobs:
 
     - name: Report Job, Run and Runner Details
       run: |
-        # Display various details about the job, run, and runner
         echo "----- JOB, RUN AND RUNNER DETAILS -----"
         echo "Job Name: ${{ github.job }}"
         echo "Event ID: ${{ github.run_id }}"
@@ -108,9 +122,7 @@ jobs:
       run: rm $RUNNER_TEMP/payload.sha
 
     - name: Set default job status
-      run: |
-        # By default, assume the job is successful
-        echo "JOB_STATUS=success" >> $GITHUB_ENV
+      run: echo "JOB_STATUS=success" >> $GITHUB_ENV
 
     - name: Set failure status if any step failed
       run: |
@@ -129,35 +141,34 @@ jobs:
           "description": "Result from Workflow ${{ github.workflow }}",
           "context": "status/${{ github.workflow }}"
         }')
-        # Check for failure (non-200 status codes)
         if [[ "$RESPONSE" -ne 200 ]]; then
-            echo "##[error] Failed to publish status. HTTP Code: $RESPONSE"
-            exit 2
+          echo "##[error] Failed to publish status. HTTP Code: $RESPONSE"
+          exit 3
         else
-            echo "##[debug] Successfully published status for ${{ github.workflow }}."
+          echo "##[debug] Successfully published status for ${{ github.workflow }}."
         fi
 
-    - name: Trigger Dependency Caching Workflow # workflow-caching.yml
+    - name: Trigger Dependency Caching Workflow # 01-cache-dependencies.yml
+      if: success()      
       run: |
-        BASE="{\"event_type\": \"trigger-cache-dependencies\", \"client_payload\": {"
+        trigger="trigger-cache-dependencies"
+        BASE="{\"event_type\": \"$trigger\", \"client_payload\": {"
         SHA="\"sha\": \"${{ env.SHA }}\","
         CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
-        BRANCH="\"branch_name\": \"${{ env.BRANCH_NAME }}\""
+        BRANCH="\"branch_name\": \"${{ env.SHA_BRANCH }}\""
         END="}}"
         PAYLOAD="$BASE$SHA$CSPROJ$BRANCH$END"
-
+    
         CMD="curl -s -o /dev/null -w \"%{http_code}\" -X POST "
         CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
         CMD+="-H \"Accept: application/vnd.github.v3+json\" "
         CMD+="-d '$PAYLOAD' "
         CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches"
-        RESPONSE=$(eval "$CMD")
+        RESPONSE=$("${CMD[@]}")
 
-        # Check for failure (non-200 status codes)
         if [[ "$RESPONSE" -ne 200 ]]; then
-            echo "##[error] Failed to trigger Dependency Caching Workflow. HTTP Code: $RESPONSE"
-            exit 4
+          echo "##[error] ${{ github.workflow }} failed to ${trigger} workflow for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+          exit 4
         else
-            echo "##[debug] Successfully Triggered Dependency Caching Workflow for ${{ env.SHA }}."
-        fi
-
+          echo "##[debug] ${{ github.workflow }}  ${trigger} workflow succeeded for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+        fi    
diff --git a/.github/workflows/01-cache-dependencies.yml b/.github/workflows/01-cache-dependencies.yml
--- a/.github/workflows/01-cache-dependencies.yml
+++ b/.github/workflows/01-cache-dependencies.yml
@@ -1,37 +1,53 @@
 ---
 name: "Cache Dependencies"
 
+# Caches reusable dependencies such as nuget packages
+
+# Exit Codes
+# 1: Failed to publish status from workflow
+# 2: Curl command to trigger next workflow failed
+ 
 on:
   repository_dispatch:
     types: trigger-cache-dependencies
 
+env:
+  # Environmental values pre-validated
+  SHA: ${{ github.event.client_payload.sha }}
+  SHA_BRANCH: ${{ github.event.client_payload.branch_name }}
+  CSPROJ: ${{ github.event.client_payload.csproj }}
+
 jobs:
+
   prepare-dotnet:
+
+    name: Cache Dependencies
     runs-on: ubuntu-latest
+    timeout-minutes: 15
+    if: (github.actor != 'CodeApprover')
 
     steps:
 
-    - name: Report SHA and Workflow Timestamp
-      run: |
-        echo "Received SHA: ${{ github.event.client_payload.sha }}"
-        date
-
-    - name: Checkout Repository
+    - name: Checkout SHA Repository
+      id: checkout-sha
       uses: actions/checkout@v3.5.3
       with:
-        ref: ${{ github.event.client_payload.sha }}
+        ref: ${{ env.SHA }}
+        fetch-depth: 0
 
-    - name: Check csproj Existence
+    - name: Report
       run: |
-        if [[ ! -f ${{ github.event.client_payload.csproj }} ]]; then
-          echo "Error: .csproj file not found at path: ${{ github.event.client_payload.csproj }}"
-          exit 1
-        fi
+        echo "##[debug] Checking initial state"
+        date
+        echo "SHA=${{ env.SHA }}"
+        echo "Environment=${{ env.SHA_BRANCH }}"
+        echo "Branch=${{ env.SHA_BRANCH }}"
+        echo "Committer=$(git log -1 --pretty=format:'%an')"
 
     - name: Restore Dependencies
       run: |
-        echo "Restoring .NET dependencies for ${{ github.event.client_payload.csproj }}"
-        dotnet restore ${{ github.event.client_payload.csproj }}
+        echo "Restoring .NET dependencies for ${{ env.CSPROJ }}"
+        dotnet restore ${{ env.CSPROJ }}
 
     # Cache .NET dependencies for faster subsequent workflow runs
     - name: Cache dotnet Dependencies
@@ -39,30 +55,59 @@ jobs:
       uses: actions/cache@v3
       with:
         path: ~/.nuget/packages
-        key: ${{ runner.os }}-dotnet-${{ github.event.client_payload.sha }}
+        key: ${{ runner.os }}-dotnet-${{ env.SHA }}
         restore-keys: |
           ${{ runner.os }}-dotnet-
 
-    - name: Trigger Stylecop Workflow # linter-stylecop.yml
+    - name: Set default job status
+      run: echo "JOB_STATUS=success" >> $GITHUB_ENV
+
+    - name: Set failure status if any step failed
       run: |
-        BASE="{\"event_type\": \"trigger-stylecop-linting\", \"client_payload\": {"
-        CSPROJ="\"csproj\": \"${{ github.event.client_payload.csproj }}\","
-        SHA="\"sha\": \"${{ github.event.client_payload.sha }}\""
+        echo "##[error] Failed detected in previous steps"
+        echo "JOB_STATUS=failure" >> $GITHUB_ENV
+      if: failure()
+
+    - name: Publish success or failure status for tracking
+      run: |
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+        -H "Authorization: token ${{ secrets.AUTH }}" \
+        -H "Accept: application/vnd.github.v3+json" \
+        https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.sha }} \
+        -d '{
+          "state": "${{ env.JOB_STATUS }}", 
+          "description": "Result from Workflow ${{ github.workflow }}",
+          "context": "status/${{ github.workflow }}"
+        }')
+        # Check for failure (non-200 status codes)
+        if [[ "$RESPONSE" -ne 200 ]]; then
+            echo "##[error] Failed to publish status for ${{ env.SHA }} HTTP Code: $RESPONSE"
+            exit 1
+        else
+            echo "##[debug] Successfully published status for ${{ env.SHA }} HTTP Code: $RESPONSE"
+        f
+
+    - name: Trigger Stylecop Workflow # 02-stylecop-linter.yml
+      if: success()  
+      run: |
+        trigger="trigger-stylecop-linter"
+        BASE="{\"event_type\": \"$trigger\", \"client_payload\": {"
+        SHA="\"sha\": \"${{ env.SHA }}\","
+        CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
+        BRANCH="\"branch_name\": \"${{ env.SHA_BRANCH }}\""
         END="}}"
-        PAYLOAD="$BASE$CSPROJ$SHA$END"
+        PAYLOAD="$BASE$SHA$CSPROJ$BRANCH$END"
     
         CMD="curl -s -o /dev/null -w \"%{http_code}\" -X POST "
         CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
         CMD+="-H \"Accept: application/vnd.github.v3+json\" "
         CMD+="-d '$PAYLOAD' "
         CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches"
-        RESPONSE=$(eval "$CMD")
-    
-        # Check for failure (non-200 status codes)
-        if [[ "$RESPONSE" -ne 200 ]]; then
-            echo "##[error] Failed to trigger Stylecop Workflow. HTTP Code: $RESPONSE"
-            exit 1
-        else
-            echo "##[debug] Successfully Triggered Stylecop Workflow for ${{ github.event.client_payload.sha }}."
-        fi
+        RESPONSE=$("${CMD[@]}")
 
+        if [[ "$RESPONSE" -ne 200 ]]; then
+          echo "##[error] ${{ github.workflow }} failed to ${trigger} workflow for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+          exit 2
+        else
+          echo "##[debug] ${{ github.workflow }}  ${trigger} workflow succeeded for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+        fi
diff --git a/.github/workflows/02-stylecop-linter.yml b/.github/workflows/02-stylecop-linter.yml
--- a/.github/workflows/02-stylecop-linter.yml
+++ b/.github/workflows/02-stylecop-linter.yml
@@ -1,28 +1,29 @@
 ---
 name: "StyleCop Linter"
 
-# Lints all commits on all valid branches
+# Lints all commits on all valid branches for CSharp compliance
 
-# Exit Codes:
-# 1: Checkout Error
+# Exit Codes
+# 1: SHA checkout failure
 # 2: Dotnet restore error
-# 3: Dotnet build error
-# 4: Unexpected environment name
-# 5: Curl command to trigger tests failed
+# 3: Dotnet stylecop build error
+# 4: Failed to publish status from workflow
+# 5: Curl command to trigger next workflow failed
 
 on:
   repository_dispatch:
-    types: "trigger-stylecop-linting"
+    types: "trigger-stylecop-linter"
 
 env:
-  PROJ_NAME: "Blazor-SqLite-Golf-Club"
+  # Pre-validated values
   SHA: ${{ github.event.client_payload.sha }}
-  BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
+  SHA_BRANCH: ${{ github.event.client_payload.branch_name }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
 
 jobs:
 
   stylecop-linting:
+
     name: StyleCop Linting
     runs-on: ubuntu-latest
     timeout-minutes: 15
@@ -31,25 +32,28 @@ jobs:
     steps:
 
     - name: Checkout SHA Repository
+      id: checkout
       uses: actions/checkout@v3.5.3
       with:
         ref: ${{ env.SHA }}
-        fetch-depth: 0 # Fetch all
-      continue-on-error: true
+        fetch-depth: 0
 
-    - name: Handle checkout error
-      if: steps.checkout.outcome == 'failure'
+    - name: Handle checkout Outcome
       run: |
-        echo "##[error] Error during checkout"
-        exit 1
+        if [[ "${{ steps.checkout-sha.outcome }}" == "failure" ]]; then
+          echo "##[error] Failure during checkout of SHA $${{ env.SHA }} on branch ${{ env.SHA_BRANCH }}."
+          exit 1
+        else
+          echo "##[debug] Successful checkout of SHA $${{ env.SHA }} on branch ${{ env.SHA_BRANCH }}."
+        fi
 
     - name: Report
       run: |
         echo "##[debug] Checking initial state"
         date
         echo "SHA=${{ env.SHA }}"
-        echo "Environment=${{ env.BRANCH_NAME }}"
-        echo "Branch=${{ env.BRANCH_NAME }}"
+        echo "Environment=${{ env.SHA_BRANCH }}"
+        echo "Branch=${{ env.SHA_BRANCH }}"
         echo "Committer=$(git log -1 --pretty=format:'%an')"
 
     - name: Setup .NET Environment
@@ -72,27 +76,55 @@ jobs:
 
     - name: Dotnet Build with StyleCop
       run: |
-        dotnet build --no-restore "${{ env.CSPROJ }}" \
-        -v detailed \
-        /p:StyleCopEnabled=true \
-        /p:StyleCopTreatErrorsAsWarnings=false \
-        /p:StyleCopForceFullAnalysis=false || (echo "##[error] Dotnet build failed" && exit 3)
+        CMD="dotnet build --no-restore \"${{ env.CSPROJ }}\" "
+        CMD+="-v detailed "
+        CMD+="/p:StyleCopEnabled=true "
+        CMD+="/p:StyleCopTreatErrorsAsWarnings=false "
+        CMD+="/p:StyleCopForceFullAnalysis=false"
+        eval "$CMD" || (echo "##[error] Dotnet build failed" && exit 3)
 
-    - name: Trigger Appropriate Tests
-       # testing-development.yml | testing-staging.yml | testing-production.yml
+    - name: Set default job status
+      run: echo "JOB_STATUS=success" >> $GITHUB_ENV
+
+    - name: Set failure status if any step failed
+      run: |
+        echo "##[error] Failed detected in previous steps"
+        echo "JOB_STATUS=failure" >> $GITHUB_ENV
+      if: failure()
+
+    - name: Publish success or failure status for tracking
+      run: |
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+        -H "Authorization: token ${{ secrets.AUTH }}" \
+        -H "Accept: application/vnd.github.v3+json" \
+        https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.sha }} \
+        -d '{
+          "state": "${{ env.JOB_STATUS }}", 
+          "description": "Result from Workflow ${{ github.workflow }}",
+          "context": "status/${{ github.workflow }}"
+        }')
+        # Check for failure (non-200 status codes)
+        if [[ "$RESPONSE" -ne 200 ]]; then
+          echo "##[error] Failed to publish status for ${{ env.SHA }} HTTP Code: $RESPONSE"
+          exit 4
+        else
+            echo "##[debug] Successfully published status for ${{ env.SHA }} HTTP Code: $RESPONSE"
+        fi
+
+    - name: Trigger Environment Based Test Suites
+      # 03-development-tests.yml | 03-staging-tests.yml | 03-production-tests.yml
       if: success()
       run: |
-        case "${{ env.BRANCH_NAME }}" in
-          code-development) EVENT_TYPE="trigger-development-tests" ;;
-          code-staging) EVENT_TYPE="trigger-env-staging-tests" ;;
-          code-production) EVENT_TYPE="trigger-production-tests" ;;
-          *) echo "##[error] Unexpected environment name"; exit 4 ;;
+        case "${{ env.SHA_BRANCH }}" in
+          code-development) TEST_SUITE="trigger-development-tests" ;;
+          code-staging) TEST_SUITE="trigger-staging-tests" ;;
+          code-production) TEST_SUITE="trigger-production-tests" ;;
         esac
 
-        BASE="{\"event_type\": \"$EVENT_TYPE\", \"client_payload\": {"
+        BASE="{\"event_type\": \"${TEST_SUITE}\", \"client_payload\": {"
         SHA="\"sha\": \"${{ env.SHA }}\","
         CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
-        BRANCH="\"branch_name\": \"${{ env.BRANCH_NAME }}\""
+        BRANCH="\"branch_name\": \"${{ env.SHA_BRANCH }}\""
         END="}}"
         PAYLOAD="$BASE$SHA$CSPROJ$BRANCH$END"
 
@@ -100,11 +132,12 @@ jobs:
         CMD+=("-H" "Authorization: Bearer ${{ secrets.AUTH }}")
         CMD+=("-H" "Accept: application/vnd.github.v3+json")
         CMD+=("-d" "$PAYLOAD")
-        CMD+=("https://api.github.com/repos/${{ github.repository }}/dispatches")  
+        CMD+=("https://api.github.com/repos/${{ github.repository }}/dispatches")
         RESPONSE=$("${CMD[@]}")
-        if [ $? -ne 0 ]; then
-            echo "##[error] Failed to trigger tests for $EVENT_TYPE."
-            exit 5
+
+        if [[ "$RESPONSE" -ne 200 ]]; then
+          echo "##[error] ${{ github.workflow }} failed to ${TEST_SUITE} workflow for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+          exit 5
         else
-            echo "##[debug] Successfully triggered tests for $EVENT_TYPE."
+           echo "##[debug] ${{ github.workflow }}  ${TEST_SUITE} workflow succeeded for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
         fi
diff --git a/.github/workflows/03-development-tests.yml b/.github/workflows/03-development-tests.yml
--- a/.github/workflows/03-development-tests.yml
+++ b/.github/workflows/03-development-tests.yml
@@ -1,15 +1,26 @@
+---
 name: "Development Tests"
+
+# Runs Development Environment Test Suite (code-development)
+
+# Exit Codes
+# 1: SHA checkout failure
+# 2: Failed to publish status from workflow
+# 3: Curl command to trigger next workflow failed
 
 on:
   repository_dispatch:
     types: "trigger-development-tests"
 
 env:
-  PROJ_NAME: "Blazor-SqLite-Golf-Club"
+  # Pre-validated values
+  SHA: ${{ github.event.client_payload.sha }}
+  SHA_BRANCH: ${{ github.event.client_payload.branch_name }}
+  CSPROJ: ${{ github.event.client_payload.csproj }}
 
 jobs:
 
-  development-testing:
+  development-tests:
 
     name: Unit Tests (${{ matrix.test_framework }})
     runs-on: ubuntu-latest
@@ -25,29 +36,42 @@ jobs:
 
     steps:
 
-    - name: Report SHA and workflow timestamp
-      run: |
-        echo "${{ github.event.client_payload.sha }}"
-        date
-
-    - name: Checkout SHA repository
+    - name: Checkout SHA Repository
+      id: checkout-sha
       uses: actions/checkout@v3.5.3
       with:
-        ref: ${{ github.event.client_payload.sha }}
-        fetch-depth: 0 # Fetch all
+        ref: ${{ env.SHA }}
+        fetch-depth: 0
 
-    # Added cache retrieval step
+    - name: Handle checkout Outcome
+      run: |
+        if [[ "${{ steps.checkout-sha.outcome }}" == "failure" ]]; then
+          echo "##[error] Failure during checkout of SHA $${{ env.SHA }} on branch ${{ env.SHA_BRANCH }}."
+          exit 1
+        else
+          echo "##[debug] Successful checkout of SHA $${{ env.SHA }} on branch ${{ env.SHA_BRANCH }}."
+        fi
+
+    - name: Report
+      run: |
+        echo "##[debug] Checking initial state"
+        date
+        echo "SHA=${{ env.SHA }}"
+        echo "Environment=${{ env.SHA_BRANCH }}"
+        echo "Branch=${{ env.SHA_BRANCH }}"
+        echo "Committer=$(git log -1 --pretty=format:'%an')"
+
     - name: Retrieve Cached dotnet Dependencies
       id: cache-dotnet-restore
       uses: actions/cache@v3
       with:
         path: ~/.nuget/packages
-        key: ${{ runner.os }}-dotnet-${{ env.BRANCH_NAME }}
+        key: ${{ runner.os }}-dotnet-${{ env.SHA }}
         restore-keys: |
           ${{ runner.os }}-dotnet-
 
     - name: Install dependencies
-      if: steps.cache-dotnet-restore.outputs.cache-hit != 'true' # Only if cache was not hit
+      if: steps.cache-dotnet-restore.outputs.cache-hit != 'true'
       run: |
         if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
           test_type="Nunit_Player_Unit_Tests"
@@ -73,20 +97,71 @@ jobs:
         CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
         eval "$CMD"
 
+  report-test-status:
+
+    name: Report Test Status
+    runs-on: ubuntu-latest
+    needs: development-tests
+
+    steps:
+
+    - name: Set default job status
+      run: echo "JOB_STATUS=success" >> $GITHUB_ENV
+
+    - name: Set failure status if any step failed
+      run: |
+        echo "##[error] Failure detected in previous steps"
+        echo "JOB_STATUS=failure" >> $GITHUB_ENV
+      if: always() && needs.development-tests.result == 'failure'
+
+    - name: Publish success or failure status for tracking
+      run: |
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+        -H "Authorization: token ${{ secrets.AUTH }}" \
+        -H "Accept: application/vnd.github.v3+json" \
+        https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.SHA }} \
+        -d '{
+          "state": "${{ env.JOB_STATUS }}", 
+          "description": "Result from Workflow ${{ github.workflow }}",
+          "context": "status/${{ github.workflow }}"
+        }')
+        # Check for failure (non-200 status codes)
+        if [[ "$RESPONSE" -ne 200 ]]; then
+          echo "##[error] Failed to publish status. HTTP Code: $RESPONSE"
+          exit 2
+        else
+          echo "##[debug] Successfully published status for ${{ env.SHA }}."
+        fi
+
   trigger-next-workflow:
 
     name: Trigger Next Workflow
     runs-on: ubuntu-latest
-    needs: development-testing
+    needs: development-tests
     timeout-minutes: 15
 
     steps:
 
-    - name: Trigger Lock File Check
+    - name: Trigger LockFile Checker Workflow # 04-lockfile-checker.yml
       run: |
-        CMD="curl -X POST -H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
+        trigger="trigger-lockfile-checker"
+        BASE="{\"event_type\": \"$trigger\", \"client_payload\": {"
+        SHA="\"sha\": \"${{ env.SHA }}\","
+        CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
+        BRANCH="\"branch_name\": \"${{ env.SHA_BRANCH }}\""
+        END="}}"
+        PAYLOAD="$BASE$SHA$CSPROJ$BRANCH$END"
+    
+        CMD="curl -s -o /dev/null -w \"%{http_code}\" -X POST "
+        CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
         CMD+="-H \"Accept: application/vnd.github.v3+json\" "
-        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
-        CMD+="-d '{\"event_type\": \"trigger-check-lock-file\", "
-        CMD+="\"client_payload\": {\"sha\": \"${{ github.event.client_payload.sha }}\"}}'"
-        eval ${CMD}
+        CMD+="-d '$PAYLOAD' "
+        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches"
+        RESPONSE=$("${CMD[@]}")
+
+        if [[ "$RESPONSE" -ne 200 ]]; then
+          echo "##[error] ${{ github.workflow }} failed to ${trigger} workflow for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+          exit 3
+        else
+          echo "##[debug] ${{ github.workflow }}  ${trigger} workflow succeeded for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+        fi
diff --git a/.github/workflows/03-staging-tests.yml b/.github/workflows/03-staging-tests.yml
--- a/.github/workflows/03-staging-tests.yml
+++ b/.github/workflows/03-staging-tests.yml
@@ -7,23 +7,42 @@ on:
     types: "trigger-staging-tests"
 
 env:
-  PROJ_NAME: "Blazor-SqLite-Golf-Club"
+  SHA: ${{ github.event.client_payload.sha }}
+  SHA_BRANCH: ${{ github.event.client_payload.branch_name }}
+  CSPROJ: ${{ github.event.client_payload.csproj }}
 
 jobs:
 
-  staging-tests:
-  
+  staging-test-suite:
+
+    name: Staging Tests
     runs-on: ubuntu-latest
     timeout-minutes: 15
     if: (github.actor != 'CodeApprover')
 
-    environment:
-      staging
-
     steps:
-    
-    - name: Report SHA and workflow timestamp
+
+    - name: Checkout SHA Repository
+      id: checkout-sha
+      uses: actions/checkout@v3.5.3
+      with:
+        ref: ${{ env.SHA }}
+        fetch-depth: 0 # Fetch all
+
+    - name: Handle checkout outcome
       run: |
-        echo "${{ github.event.client_payload.sha }}"
+        if [[ "${{ steps.checkout-sha.outcome }}" == "failure" ]]; then
+          echo "##[error] Error during checkout of SHA $${{ env.SHA }} on branch ${{ env.SHA_BRANCH }}"
+          exit 1
+        else
+          echo "Checkout was successful"
+        fi
+
+    - name: Report
+      run: |
+        echo "##[debug] Checking initial state"
         date
- 
+        echo "SHA=${{ env.SHA }}"
+        echo "Environment=${{ env.SHA_BRANCH }}"
+        echo "Branch=${{ env.SHA_BRANCH }}"
+        echo "Committer=$(git log -1 --pretty=format:'%an')"
diff --git a/.github/workflows/04-lockfile-checker.yml b/.github/workflows/04-lockfile-checker.yml
--- a/.github/workflows/04-lockfile-checker.yml
+++ b/.github/workflows/04-lockfile-checker.yml
@@ -1,16 +1,22 @@
 ---
 name: "Check Lock File"
 
-# Exit Code Commentary:
-# 1 - The commit SHA does not exist
-# 2 - Failed to push the lock file
-# 3 - Lock file was not successfully created or pushed
+# Workflow to manage lock files for sequential task execution within a branch.
+
+# Exit Codes
+# 1: Failed to checkout SHA branch on retry
+# 2: Failed to push lock file
+# 3: Failed to fetch branch
+# 4: Failed to detect pushed lock file
+# 5: Failed to publish status from workflow
+# 6: Curl command to trigger next workflow failed
 
 on:
   repository_dispatch:
-    types: trigger-check-lock-file
+    types: trigger-lockfile-checker
 
 env:
+  # Pre-validated values / repository variables
   SHA: ${{ github.event.client_payload.sha }}
   BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
@@ -18,98 +24,144 @@ env:
   SLEEP_MINUTES: ${{ secrets.SLEEP_MINUTES }}
 
 jobs:
+
   check-for-lock-file:
+
     runs-on: ubuntu-latest
     timeout-minutes: 15
     if: (github.actor != 'CodeApprover')
     
     steps:
-      - name: Checkout SHA Repository
-        uses: actions/checkout@v3.5.3
-        with:
-          ref: ${{ env.SHA }}
-          fetch-depth: 0
 
-      - name: Report
-        run: |
-          date
-          echo "SHA=${{ env.SHA }}"
-          branch_name=${{ env.BRANCH_NAME }}
-          echo "Environment=$(echo $branch_name | sed 's#code-##')"
-          echo "Branch=${{ env.BRANCH_NAME }}"
-          echo "Committer=$(git log -1 --pretty=format:'%an')"
+    - name: Checkout SHA Repository
+      id: checkout
+      uses: actions/checkout@v3.5.3
+      with:
+        ref: ${{ env.SHA }}
+        fetch-depth: 0
 
-      - name: Configure Git User and Email
-        run: |
-          git config user.name "CodeApprover"
-          git config user.email "pucfada@pm.me"
+    - name: Report
+      run: |
+        date
+        echo "SHA=${{ env.SHA }}"
+        branch_name=${{ env.SHA_BRANCH }}
+        echo "Environment=$(echo $branch_name | sed 's#code-##')"
+        echo "Branch=${{ env.SHA_BRANCH }}"
+        echo "Committer=$(git log -1 --pretty=format:'%an')"
 
-      - name: Set Lock File Name Based on Branch
-        run: |
-          branch=${{ env.BRANCH_NAME }}
-          if [[ $branch == "code-"* ]]; then
-              lock_name=${branch#code-}
-              echo "LOCK_FILE=.$lock_name.lock" >> $GITHUB_ENV
-          elif [[ $branch == "main" ]]; then
-              echo "LOCK_FILE=.main.lock" >> $GITHUB_ENV
-          fi
+    - name: Configure Git User and Email
+      run: |
+        git config user.name "CodeApprover"
+        git config user.email "pucfada@pm.me"
 
-      - name: Check Lock File with Retry
-        run: |
-          for (( i=1; i<=${{ env.MAX_RETRIES }}; i++ )); do
-            echo "::group::Attempt $i"
-            git fetch origin ${{ env.BRANCH_NAME }}
-            git checkout ${{ env.BRANCH_NAME }}
-            if [ $? -ne 0 ]; then
-              echo "::error::Failed to checkout ${{ env.BRANCH_NAME }}"
-              exit 5
-            fi
+    - name: Set Lock File Name Based on Branch
+      run: |
+        branch=${{ env.BRANCH_NAME }}
+        if [[ $branch == "code-"* ]]; then
+            lock_name=${branch#code-}
+            echo "LOCK_FILE=.$lock_name.lock" >> $GITHUB_ENV
+        elif [[ $branch == "main" ]]; then
+            echo "LOCK_FILE=.main.lock" >> $GITHUB_ENV
+        fi
 
-            commits_before_sha=$(git rev-list ${{ env.SHA }}~1..${{ env.BRANCH_NAME }} --)
+    - name: Check Lock File with Retry
+      run: |
+        for (( i=1; i<=${{ env.MAX_RETRIES }}; i++ )); do
+        echo "::group::Attempt $i"
+        git fetch origin ${{ env.BRANCH_NAME }}
+        git checkout ${{ env.BRANCH_NAME }}
+        if [ $? -ne 0 ]; then
+            echo "::error::Failed to checkout ${{ env.BRANCH_NAME }}"
+            exit 1
+        fi
 
-            if git ls-tree -r $commits_before_sha | grep "${{ env.LOCK_FILE }}"; then
-              echo "Lock file found. Waiting ${{ env.SLEEP_MINUTES }} minutes before retrying."
-              sleep $((${{ env.SLEEP_MINUTES }} * 60))
-            else
-              break
-            fi
-            echo "::endgroup::"
-          done
+        commits_before_sha=$(git rev-list ${{ env.SHA }}~1..${{ env.BRANCH_NAME }} --)
 
-          echo "${{ env.SHA }}" > "${{ env.LOCK_FILE }}"
-          git add "${{ env.LOCK_FILE }}"
-          git commit -m "Adding ${{ env.LOCK_FILE }} for ${{ env.SHA }} [skip ci]."
+        if git ls-tree -r $commits_before_sha | grep "${{ env.LOCK_FILE }}"; then
+            echo "Lock file found. Waiting ${{ env.SLEEP_MINUTES }} minutes before retrying."
+            sleep $((${{ env.SLEEP_MINUTES }} * 60))
+        else
+            break
+        fi
+        echo "::endgroup::"
+        done
 
-          if ! git push origin HEAD:${{ env.BRANCH_NAME }}; then
-            echo "::error::Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}"
-            exit 2
-          fi
+        echo "${{ env.SHA }}" > "${{ env.LOCK_FILE }}"
+        git add "${{ env.LOCK_FILE }}"
+        git commit -m "Adding ${{ env.LOCK_FILE }} for ${{ env.SHA }} [skip ci]."
 
-          git fetch origin ${{ env.BRANCH_NAME }}
-          if [ $? -ne 0 ]; then
-            echo "::error::Failed to fetch ${{ env.BRANCH_NAME }}"
-            exit 4
-          fi
+        if ! git push origin HEAD:${{ env.BRANCH_NAME }}; then
+        echo "::error::Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}"
+        exit 2
+        fi
 
-          if ! git ls-tree HEAD -- ${{ env.LOCK_FILE }}; then
-            echo "::error::Lock file ${{ env.LOCK_FILE }} was not successfully created or pushed."
-            exit 3
-          else
-            echo "Lock file ${{ env.LOCK_FILE }} successfully created and pushed."
-          fi
+        git fetch origin ${{ env.BRANCH_NAME }}
+        if [ $? -ne 0 ]; then
+        echo "::error::Failed to fetch ${{ env.BRANCH_NAME }}"
+        exit 3
+        fi
 
-      - name: Trigger Versioning Workflow
-        if: success()
-        uses: actions/github-script@v5
-        with:
-          script: |
-            const repo = context.repo;
-            const payload = {
-              event_type: "trigger-versioning",
-              client_payload: {
-                sha: "${{ env.SHA }}",
-                branch_name: "${{ env.BRANCH_NAME }}",
-                csproj: "${{ env.CSPROJ }}"
-              }
-            };
-            await github.request(`POST /repos/${repo.owner}/${repo.repo}/dispatches`, payload);
+        if ! git ls-tree HEAD -- ${{ env.LOCK_FILE }}; then
+        echo "::error::Lock file ${{ env.LOCK_FILE }} was not detected remotely."
+        exit 4
+        else
+        echo "Lock file ${{ env.LOCK_FILE }} successfully created and pushed."
+        fi
+
+    - name: Set default job status
+      run: echo "JOB_STATUS=success" >> $GITHUB_ENV
+
+    - name: Set failure status if any step failed
+      run: |
+        echo "##[error] Failed detected in previous steps"
+        echo "JOB_STATUS=failure" >> $GITHUB_ENV
+      if: failure()
+
+    - name: Publish success or failure status for tracking
+      run: |
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+        -H "Authorization: token ${{ secrets.AUTH }}" \
+        -H "Accept: application/vnd.github.v3+json" \
+        https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.sha }} \
+        -d '{
+          "state": "${{ env.JOB_STATUS }}", 
+          "description": "Result from Workflow ${{ github.workflow }}",
+          "context": "status/${{ github.workflow }}"
+        }')
+        # Check for failure (non-200 status codes)
+        if [[ "$RESPONSE" -ne 200 ]]; then
+          echo "##[error] Failed to publish status for ${{ env.SHA }} HTTP Code: $RESPONSE"
+          exit 5
+        else
+          echo "##[debug] Successfully published status for ${{ env.SHA }} HTTP Code: $RESPONSE"
+        fi
+
+    - name: Trigger Staging and Production Code Analysis and Linting
+      if: success()
+      run: |
+        case "${{ env.SHA_BRANCH }}" in
+          code-development) TEST_SUITE="trigger-development-tests" ;;
+          code-staging) TEST_SUITE="trigger-staging-tests" ;;
+          code-production) TEST_SUITE="trigger-production-tests" ;;
+        esac
+
+        BASE="{\"event_type\": \"${TEST_SUITE}\", \"client_payload\": {"
+        SHA="\"sha\": \"${{ env.SHA }}\","
+        CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
+        BRANCH="\"branch_name\": \"${{ env.SHA_BRANCH }}\""
+        END="}}"
+        PAYLOAD="$BASE$SHA$CSPROJ$BRANCH$END"
+
+        CMD=("curl" "-X" "POST")
+        CMD+=("-H" "Authorization: Bearer ${{ secrets.AUTH }}")
+        CMD+=("-H" "Accept: application/vnd.github.v3+json")
+        CMD+=("-d" "$PAYLOAD")
+        CMD+=("https://api.github.com/repos/${{ github.repository }}/dispatches")
+        RESPONSE=$("${CMD[@]}")
+
+        if [[ "$RESPONSE" -ne 200 ]]; then
+          echo "##[error] ${{ github.workflow }} failed to ${TEST_SUITE} workflow for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+          exit 6
+        else
+          echo "##[debug] ${{ github.workflow }}  ${TEST_SUITE} workflow succeeded for ${{ env.SHA }} on branch  ${{ env.SHA_BRANCH }}. HTTP Code: $RESPONSE"
+        fi
