Update 01-cache-dependencies.yml

diff --git a/.github/workflows/01-cache-dependencies.yml b/.github/workflows/01-cache-dependencies.yml
--- a/.github/workflows/01-cache-dependencies.yml
+++ b/.github/workflows/01-cache-dependencies.yml
@@ -38,7 +38,7 @@ jobs:
     - name: Restore dotnet Dependencies
       run: |
         echo "##[info] Restoring .NET dependencies for ${{ env.CSPROJ }}"
-        run: dotnet restore --no-cache "${{ env.CSPROJ }}" -v detailed || (echo "##[error] Dotnet restore failed" && exit 34)
+        dotnet restore --no-cache "${{ env.CSPROJ }}" -v detailed || (echo "##[error] Dotnet restore failed" && exit 34)
 
     - name: Cache dotnet Dependencies
       uses: actions/cache@v3
