Update 03-00-development-tests.yml[skip ci]

diff --git a/.github/workflows/03-00-development-tests.yml b/.github/workflows/03-00-development-tests.yml
--- a/.github/workflows/03-00-development-tests.yml
+++ b/.github/workflows/03-00-development-tests.yml
@@ -50,6 +50,7 @@ jobs:
 
     - name: Install Test Suite Dependencies
       run: |
+      
         if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
           test_type="Nunit_Player_Unit_Tests"
         else
@@ -61,6 +62,7 @@ jobs:
 
     - name: Run Nunit and Xunit Unit Tests
       run: |
+      
         if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
           test_type="Nunit_Player_Unit_Tests"
           log_file_name="nunit-results.trx"
@@ -77,15 +79,16 @@ jobs:
     - name: Trigger Next Workflow
       if: success()
       run: |
-        CMD="curl -L -X POST "
-        CMD+="-H \"Accept: application/vnd.github+json\" "
-        CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
-        CMD+="-H \"X-GitHub-Api-Version: 2022-11-28\" "
-        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
-        CMD+="-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\","
-        CMD+="\"client_payload\":{"
-        CMD+="\"sha\":\"${{ github.sha }}\","
-        CMD+="\"csproj\":\"${{ env.CSPROJ }}\"}'"
+      
+        CMD=$(echo "curl -L -X POST" \
+        "-H \"Accept: application/vnd.github+json\"" \
+        "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+        "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+        "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+        "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
+        "\"client_payload\":{" \
+        "\"sha\":\"${{ env.SHA }}\"," \
+        "\"csproj\":\"${{ env.CSPROJ }}\"}'")
 
         retries=0
         while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
@@ -99,7 +102,7 @@ jobs:
                     sleep ${{ vars.WAIT_SECONDS }}
                 else
                     echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                    echo "##[error] Failed to trigger ${env.NEXT_WORKFLOW} workflow with CURL command: $CMD." && exit 90
+                    echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
                 fi
             else
                 break # successful curl
