Update 03-00-development-tests.yml [skip ci]

diff --git a/.github/workflows/03-00-development-tests.yml b/.github/workflows/03-00-development-tests.yml
--- a/.github/workflows/03-00-development-tests.yml
+++ b/.github/workflows/03-00-development-tests.yml
@@ -1,5 +1,5 @@
 ---
-name: "Development Tests"
+name: Development Tests
 
 # ${{ github.workflow }} Overview
 #
@@ -17,12 +17,12 @@ name: "Development Tests"
 
 on:
   repository_dispatch:
-    types: trigger-development-tests
+    types: Development Tests
 
 env:
   SHA: ${{ github.event.client_payload.sha }}
-  SHA_BRANCH: ${{ github.event.client_payload.sha_branch }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
+  NEXT_WORKFLOW: Lockfile-Checker
 
 jobs:
 
@@ -31,7 +31,9 @@ jobs:
     name: Unit Tests (${{ matrix.test_framework }})
     runs-on: ubuntu-latest
     timeout-minutes: 15
-    #if: github.actor != 'CodeApprover'
+
+    # un-comment to block execution
+    #if: (github.actor != ${{ github.repository_owner }})
 
     strategy:
       matrix:
@@ -41,7 +43,7 @@ jobs:
 
     - name: Checkout SHA Repository
       id: checkout-sha
-      uses: actions/checkout@v3.5.3
+      uses: actions/checkout@v3.6.0
       with:
         ref: ${{ env.SHA }}
         fetch-depth: 0
@@ -72,29 +74,35 @@ jobs:
         CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
         eval "$CMD"
 
-  trigger-next-workflow:
-
-    if: success()
-    name: Trigger Next Workflow
-    runs-on: ubuntu-latest
-    needs: development-tests
-    timeout-minutes: 15
-
-    steps:
-
-    - name: Trigger Next Workflow # 04-lockfile-checker.yml
+    - name: Trigger Next Workflow
       if: success()
       run: |
-        trigger="trigger-lockfile-checker"
-        BASE="{\"event_type\": \"$trigger\", \"client_payload\": {"
-        SHA="\"sha\": \"${{ env.SHA }}\","
-        CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
-        BRANCH="\"sha_branch\": \"${{ env.SHA_BRANCH }}\""
-        END="}}"
+        CMD="curl -L -X POST "
+        CMD+="-H \"Accept: application/vnd.github+json\" "
+        CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
+        CMD+="-H \"X-GitHub-Api-Version: 2022-11-28\" "
+        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
+        CMD+="-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\","
+        CMD+="\"client_payload\":{"
+        CMD+="\"sha\":\"${{ github.sha }}\","
+        CMD+="\"csproj\":\"${{ env.CSPROJ }}\"}'"
 
-        curl -s -o /dev/null -X POST \
-        -H "Authorization: Bearer ${{ secrets.AUTH }}" \
-        -H "Accept: application/vnd.github.v3+json" \
-        -d "$BASE$SHA$CSPROJ$BRANCH$END" \
-        "https://api.github.com/repos/${{ github.repository }}/dispatches"
-  
+        retries=0
+        while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+            eval "$CMD"
+            CURL_EXIT_CODE=$?
+            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                retries=$((retries+1))
+                if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                    echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                    sleep ${{ vars.WAIT_SECONDS }}
+                else
+                    echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                    echo "##[error] Failed to trigger ${env.NEXT_WORKFLOW} workflow with CURL command: $CMD." && exit 90
+                fi
+            else
+                break # successful curl
+            fi    
+        done
+        echo "##[debug] CURL command: $CMD"
