Update 03-development-tests.yml

diff --git a/.github/workflows/03-development-tests.yml b/.github/workflows/03-development-tests.yml
--- a/.github/workflows/03-development-tests.yml
+++ b/.github/workflows/03-development-tests.yml
@@ -25,7 +25,7 @@ jobs:
     name: Unit Tests (${{ matrix.test_framework }})
     runs-on: ubuntu-latest
     timeout-minutes: 15
-    if: github.event.client_payload.branch_name == 'code-development' # && (github.actor != 'CodeApprover')
+    #if: github.actor != 'CodeApprover'
 
     environment:
       development
@@ -50,6 +50,16 @@ jobs:
           exit 1
         else
           echo "##[debug] Successful checkout of SHA $${{ env.SHA }} on branch ${{ env.SHA_BRANCH }}."
+        fi
+
+    - name: Confirm Branch
+      run: |
+        CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
+        if [[ "$CURRENT_BRANCH" != "code-development" ]]; then
+          echo "##[error] $CURRENT_BRANCH is not code-development --> Exiting 2"
+          exit 2
+        else
+          echo "Confirmed on code-development branch."
         fi
 
     - name: Report
@@ -96,42 +106,6 @@ jobs:
         CMD+=" --logger \"trx;LogFileName=${log_file_name}\""
         CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
         eval "$CMD"
-
-  report-test-status:
-
-    name: Report Test Status
-    runs-on: ubuntu-latest
-    needs: development-tests
-
-    steps:
-
-    - name: Set default job status
-      run: echo "JOB_STATUS=success" >> $GITHUB_ENV
-
-    - name: Set failure status if any step failed
-      run: |
-        echo "##[error] Failure detected in previous steps"
-        echo "JOB_STATUS=failure" >> $GITHUB_ENV
-      if: always() && needs.development-tests.result == 'failure'
-
-    - name: Publish success or failure status for tracking
-      run: |
-        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
-        -H "Authorization: token ${{ secrets.AUTH }}" \
-        -H "Accept: application/vnd.github.v3+json" \
-        https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.SHA }} \
-        -d '{
-          "state": "${{ env.JOB_STATUS }}", 
-          "description": "Result from Workflow ${{ github.workflow }}",
-          "context": "status/${{ github.workflow }}"
-        }')
-        # Check for failure (non-200 status codes)
-        if [[ "$RESPONSE" -ne 200 ]]; then
-          echo "##[error] Failed to publish status. HTTP Code: $RESPONSE"
-          exit 2
-        else
-          echo "##[debug] Successfully published status for ${{ env.SHA }}."
-        fi
 
   trigger-next-workflow:
 
