Update 04-03-deploy-git.yml[skip ci]

diff --git a/.github/workflows/04-03-deploy-git.yml b/.github/workflows/04-03-deploy-git.yml
--- a/.github/workflows/04-03-deploy-git.yml
+++ b/.github/workflows/04-03-deploy-git.yml
@@ -123,6 +123,23 @@ jobs:
         latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
         TAG_MESSAGE=$(git tag -l --format='%(contents)' $latest_tag)
 
+    # Step 8 - Unset the lockfile
+    - name: Set SHA Gist as Locked
+      run: |
+ 
+        create_response=$(curl -s -X PATCH \
+          -H "Authorization: token ${{ secrets.AUTH }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          -d "{\"files\": {\"lockfile.lock\": {\"content\": \"\"}}}" \
+          "https://api.github.com/gists/${{ vars.SHA_GIST }}")
+        gist_id=$(echo "$create_response" | jq -r '.id')
+        if [[ -z "$gist_id" ]]; then
+          echo "Failed to set lock."
+          exit 32
+        else
+          echo "Lock set successfully."
+        fi
+
     # Step 8: Trigger the next workflow if Git deployment is successful.
     - name: Trigger Next Workflow
       run: |
