Update 04-03-deploy-git.yml[skip ci]

diff --git a/.github/workflows/04-03-deploy-git.yml b/.github/workflows/04-03-deploy-git.yml
--- a/.github/workflows/04-03-deploy-git.yml
+++ b/.github/workflows/04-03-deploy-git.yml
@@ -25,7 +25,7 @@ jobs:
 
       - name: Configure Git User
         run: |
-
+ 
           git config user.name "${{ github.repository_owner}}"
           git config user.email "${{ vars.EMAIL }}"
           if [ $? -ne 0 ]; then
@@ -33,45 +33,44 @@ jobs:
           fi
           echo "##[debug] Git user configured successfully."
 
-      - name: Reset Lock File holding Commit SHA
+      - name: Unlock SHA Gist
         run: |
+   
+          # Update Gist to have no content, to unset lock
+          echo "##[debug][gist] Clearing the SHA Gist of the current SHA."
+          gist_id="${{ vars.SHA_GIST }}"
+   
+          CURL_CMD=$(echo "curl -L \
+            -X PATCH \
+            -H \"Accept: application/vnd.github+json\" \
+            -H \"Authorization: token ${{ secrets.AUTH }}\" \
+            -H \"X-GitHub-Api-Version: 2022-11-28\" \
+            https://api.github.com/gists/$gist_id \
+            -d '{\"files\": {\"auth-gate.sha\": {\"content\": \"\"}}}'")
 
-          echo "##[debug] Beginning reset of lock file holding commit SHA."
-          declare -A branch_lock_map
-          branch_lock_map["code-production"]=".production.lock"
-          branch_lock_map["code-staging"]=".staging.lock"
-          branch_lock_map["code-development"]=".development.lock"
-          branch_lock_map["main"]=".main.lock"
-          lock_file=${branch_lock_map[${{ env.SHA_BRANCH }}]}
-          git fetch --all
-          git pull origin ${{ env.SHA_BRANCH }}
-          if [ $? -ne 0 ]; then
-            echo "##[error] Failed to pull from repository." && exit 41
-          fi
-          echo "##[debug] lockfile $lock_file contents: $(cat .development.lock)"
-          newer_commits=5
-          commits_to_check=$(git log -n ${newer_commits} --format="%H")
-          echo "##[debug] Commits to check: $commits_to_check"
-          commit_with_lockfile=""
-          for commit in $commits_to_check; do
-            if git show "$commit:$lock_file" 2>/dev/null | grep -q "${{ env.SHA }}"; then
-              commit_with_lockfile=$commit
+          eval "$CURL_CMD"
+          if [[ $? -ne 0 ]]; then
+            echo "##[error][gist] Failed to update Gist with blank content."
+            exit 32
+          else
+            # Check SHA GIST for content
+            content=$(curl -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: token ${{ secrets.AUTH }}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/gists/$gist_id | jq '.files["auth-gate.sha"].content' -r)
+  
+            if [ "$content" == "" ]; then
+              echo "##[debug][gist] Gist updated successfully. Lock unset."
               break
+            else
+              echo "##[error][gist] Gist has unexpected content. Attempt $((retries+1))."
             fi
-          done
-          if [ -z "$commit_with_lockfile" ]; then
-            echo "##[error] Lock file with correct SHA not found in the next 5 commits!" && exit 42
           fi
-          echo "##[debug] Reverting the commit that added the lock file."
-          git revert $commit_with_lockfile --no-edit
-          if [ $? -ne 0 ]; then
-            echo "##[error] Failed to revert the lockfile $lock_file commit $commit_with_lockfile" && exit 43
-          fi
-          echo "##[info] Successfully reverted lockfile."
 
-      - name: Set Deployment Environments
+      - name: Set Deployment Branches and Directories
         run: |
-
+ 
           deploy_branches=()
           directory=""
 
@@ -99,7 +98,7 @@ jobs:
 
       - name: Reset all branches to mirror main if push is to main
         run: |
-
+ 
           if [[ "${{ env.SHA_BRANCH }}" == "main" ]]; then
               for target_branch in code-development code-staging code-production; do
                   git fetch origin
@@ -111,7 +110,7 @@ jobs:
 
       - name: Set and Copy Source Directory to Temp Dir
         run: |
-
+ 
           src_dir=${{ env.SHA_BRANCH }}
           src_dir=${src_dir#code-}
           dir_path=$(find ${{ github.workspace }} -type d -name "$src_dir" -print | head -n 1)
@@ -124,7 +123,7 @@ jobs:
 
       - name: Deploy to Target Branches
         run: |
-
+ 
           if [[ "${{ env.SHA_BRANCH }}" != "main" ]]; then
               echo "##[info] Deploying commit ${{ env.SHA }} to target branches."
               latest_tag=$(git tag -l 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1) # v1.2.3 SemVer
@@ -152,7 +151,7 @@ jobs:
       - name: Trigger Next Workflow
         if: success()
         run: |
-
+ 
           CMD=$(echo "curl -L -X POST" \
             "-H \"Accept: application/vnd.github+json\"" \
             "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
