Update 04-01-versioning.yml [skip ci]

diff --git a/.github/workflows/04-01-versioning.yml b/.github/workflows/04-01-versioning.yml
--- a/.github/workflows/04-01-versioning.yml
+++ b/.github/workflows/04-01-versioning.yml
@@ -1,5 +1,5 @@
 ---
-name: "Versioning"
+name: Versioning
 
 # Sets a version number for the SHA commint using SemVer 2.0 notation.
 # Triggered by a repository_dispatch event "trigger-versioning".
@@ -18,30 +18,34 @@ name: "Versioning"
 
 on:
   repository_dispatch:
-    types: trigger-versioning
+    types: Versioning
 
 env:
   SHA: ${{ github.event.client_payload.sha }}
-  SHA_BRANCH: ${{ github.event.client_payload.sha_branch }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
-  PROJ_NAME: "Blazor-SqLite-Golf-Club"
-  CURRENT_TAG: ""
-  NEW_VERSION: ""
+  NEXT_WORKFLOW: Deploy Docker
 
 jobs:
   version-and-tag:
     runs-on: ubuntu-latest
     timeout-minutes: 15
-    #if: (github.actor != 'CodeApprover')
+
+    # un-comment to block execution
+    #if: (github.actor != ${{ github.repository_owner }})
 
     steps:
 
       - name: Checkout SHA repository
-        uses: actions/checkout@v3.5.3
+        uses: actions/checkout@v3.6.0
         with:
           ref: ${{ env.SHA }}
           fetch-depth: 0
         continue-on-error: true
+
+      - name: Configure Git User
+        run: |
+          git config user.name "${{ github.repository_owner}}"
+          git config user.email "${{ vars.EMAIL }}"
 
       - name: Fetch Versioning Tags
         run: |
@@ -53,8 +57,6 @@ jobs:
 
       - name: Clean Redundant Versioning Tags
         run: |
-          git config user.name "CodeApprover"
-          git config user.email "pucfada@pm.me"
           echo "##[info] Deleting versioning tags skipping the 12 most recent."
           DELETE_TAGS=$(git tag -l | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n -12)
           for TAG in $DELETE_TAGS; do
@@ -62,7 +64,7 @@ jobs:
               git push origin --delete $TAG || (echo "##[error] Failed to push tag deletion." && exit 43)
           done
 
-      - name: Increment SemVer 2.0 version number
+      - name: Increment SemVer 2.0 Versioning
         run: |
           # Get the latest tag based on SemVer
           latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
@@ -75,7 +77,8 @@ jobs:
           patch=$(echo $version  | cut -d. -f3)
           
           # Increment for required environment
-          case "${{ env.SHA_BRANCH }}" in
+          branch=$(git branch --contains ${{ env.SHA }})
+          case "$branch" in
             "code-production")
               major=$((major + 1))
               minor=0
@@ -93,23 +96,40 @@ jobs:
           echo "##[debug] New version number = $new_version"
           echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
 
-      - name: Tag repository with new version
+      - name: Tag repository with New Version
         run: |
           git tag "${{ env.NEW_VERSION }}"
           git push origin "${{ env.NEW_VERSION }}" || (echo "##[error] Failed to push new tag ${{ env.NEW_VERSION }}" && exit 44)
 
-      - name: Trigger Next Workflow # 08-deploy-docker.yml
+      - name: Trigger Next Workflow
         if: success()
         run: |
-          trigger="trigger-deploy-docker"
-          BASE="{\"event_type\": \"$trigger\", \"client_payload\": {"
-          SHA="\"sha\": \"${{ env.SHA }}\","
-          CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
-          BRANCH="\"sha_branch\": \"${{ env.SHA_BRANCH }}\""
-          END="}}"
+          CMD="curl -L -X POST "
+          CMD+="-H \"Accept: application/vnd.github+json\" "
+          CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
+          CMD+="-H \"X-GitHub-Api-Version: 2022-11-28\" "
+          CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
+          CMD+="-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\","
+          CMD+="\"client_payload\":{"
+          CMD+="\"sha\":\"${{ github.sha }}\","
+          CMD+="\"csproj\":\"${{ env.CSPROJ }}\"}'"
 
-          curl -s -o /dev/null -X POST \
-          -H "Authorization: Bearer ${{ secrets.AUTH }}" \
-          -H "Accept: application/vnd.github.v3+json" \
-          -d "$BASE$SHA$CSPROJ$BRANCH$END" \
-          "https://api.github.com/repos/${{ github.repository }}/dispatches"
+          retries=0
+          while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+              eval "$CMD"
+              CURL_EXIT_CODE=$?
+              if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                  echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                  retries=$((retries+1))
+                  if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                      echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                      sleep ${{ vars.WAIT_SECONDS }}
+                  else
+                      echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                      echo "##[error] Failed to trigger ${env.NEXT_WORKFLOW} workflow with CURL command: $CMD." && exit 90
+                  fi
+              else
+                  break # successful curl
+              fi    
+          done
+          echo "##[debug] CURL command: $CMD"
