Update 04-02-deploy-docker.yml [skip ci]

diff --git a/.github/workflows/04-02-deploy-docker.yml b/.github/workflows/04-02-deploy-docker.yml
--- a/.github/workflows/04-02-deploy-docker.yml
+++ b/.github/workflows/04-02-deploy-docker.yml
@@ -1,5 +1,5 @@
 ---
-name: "Deploy Docker"
+name: Deploy Docker
 
 # Builds and pushes a Docker image of the commit SHA repository, if it doesn't exist.
 # Executes for the code-development, code-staging and code-production branches.
@@ -17,27 +17,28 @@ name: "Deploy Docker"
 # 49 - Dockerfile build failed.
 # 50 - Dockerfile push failed.
 
-
 on:
   repository_dispatch:
-    types: trigger-deploy-docker
+    types: Deploy Docker
 
 env:
   SHA: ${{ github.event.client_payload.sha }}
-  SHA_BRANCH: ${{ github.event.client_payload.sha_branch }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
+  NEXT_WORKFLOW: Deploy Git
 
 jobs:
 
   save-docker-image:
     runs-on: ubuntu-latest
     timeout-minutes: 15
-    #if: (github.actor != 'CodeApprover')
+
+    # un-comment to block execution
+    #if: (github.actor != ${{ github.repository_owner }})
 
     steps:
     
     - name: Checkout SHA repository
-      uses: actions/checkout@v3.5.3
+      uses: actions/checkout@v3.6.0
       with:
         ref: ${{ env.SHA }}
         fetch-depth: 0
@@ -71,7 +72,8 @@ jobs:
         if docker manifest inspect ${{ secrets.DOCKER_HUB_USERNAME }}/$docker_repo:${{ env.NEW_VERSION }} > /dev/null; then
             echo "Docker image already exists! Skipping Docker push."
         else
-            docker_file=$(find ./$(echo "${{ env.SHA_BRANCH }}" | sed 's/^code-//') -name "Dockerfile" | head -n 1)
+            branch=$(git branch --contains ${{ env.SHA }})
+            docker_file=$(find ./$(echo "$branch" | sed 's/^code-//') -name "Dockerfile" | head -n 1)
             if [[ ! -f "$docker_file" ]]; then
                 echo "##[error] Dockerfile not found for ${{ env.SHA }} --> Exit 48"
                 exit 48
@@ -84,18 +86,35 @@ jobs:
             eval ${CMD} || (echo "##[error] Docker push failed" && exit 50)
         fi
 
-    - name: Trigger Next Workflow # 09-deploy-git.yml
+    - name: Trigger Next Workflow
       if: success()
       run: |
-        trigger="trigger-deploy-git"
-        BASE="{\"event_type\": \"$trigger\", \"client_payload\": {"
-        SHA="\"sha\": \"${{ env.SHA }}\","
-        CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
-        BRANCH="\"sha_branch\": \"${{ env.SHA_BRANCH }}\""
-        END="}}"
+        CMD="curl -L -X POST "
+        CMD+="-H \"Accept: application/vnd.github+json\" "
+        CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
+        CMD+="-H \"X-GitHub-Api-Version: 2022-11-28\" "
+        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
+        CMD+="-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\","
+        CMD+="\"client_payload\":{"
+        CMD+="\"sha\":\"${{ github.sha }}\","
+        CMD+="\"csproj\":\"${{ env.CSPROJ }}\"}'"
 
-        curl -s -o /dev/null -X POST \
-        -H "Authorization: Bearer ${{ secrets.AUTH }}" \
-        -H "Accept: application/vnd.github.v3+json" \
-        -d "$BASE$SHA$CSPROJ$BRANCH$END" \
-        "https://api.github.com/repos/${{ github.repository }}/dispatches"
+        retries=0
+        while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+            eval "$CMD"
+            CURL_EXIT_CODE=$?
+            if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                retries=$((retries+1))
+                if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                    echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                    sleep ${{ vars.WAIT_SECONDS }}
+                else
+                    echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                    echo "##[error] Failed to trigger ${env.NEXT_WORKFLOW} workflow with CURL command: $CMD." && exit 90
+                fi
+            else
+                break # successful curl
+            fi    
+        done
+        echo "##[debug] CURL command: $CMD"
