Update 04-03-deploy-git.yml

diff --git a/.github/workflows/04-03-deploy-git.yml b/.github/workflows/04-03-deploy-git.yml
--- a/.github/workflows/04-03-deploy-git.yml
+++ b/.github/workflows/04-03-deploy-git.yml
@@ -29,6 +29,7 @@ on:
 env:
   SHA: ${{ github.event.client_payload.sha }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
+  GH_TOKEN: ${{ secrets.AUTH }}
   NEXT_WORKFLOW: Success
 
 jobs:
@@ -50,11 +51,13 @@ jobs:
 
     - name: Configure Git User
       run: |
+      
         git config user.name "${{ github.repository_owner}}"
         git config user.email "${{ vars.EMAIL }}"
 
     - name: Check for Expected Payload SHA Lock File
       run: |
+      
         branch=$(git branch --contains ${{ env.SHA }})
         echo "SHA_BRANCH=$branch" >> $GITHUB_ENV       
         declare -A branch_lock_map
@@ -71,6 +74,7 @@ jobs:
 
     - name: Set Deployment Environments
       run: |
+      
         deploy_branches=()
         directory=""
         
@@ -88,7 +92,7 @@ jobs:
             directory="production"
             ;;
            "main")
-            echo "##[info]# No deployment required for ${{ env.sha_branch }}"
+            echo "##[info] No deployment required for ${{ env.sha_branch }}"
             ;;
         esac
 
@@ -97,6 +101,7 @@ jobs:
 
     - name: Set and Copy Source Directory to Temp Dir
       run: |
+      
         src_dir=${{ env.sha_branch }}
         src_dir=${src_dir#code-}
         dir_path=$(find ${{ github.workspace }} -type d -name "$src_dir" -print | head -n 1)
@@ -110,7 +115,8 @@ jobs:
 
     - name: Deploy to Target Branches
       run: |
-        echo "##[info]# Deploying commit ${{ env.SHA }} to target branches."
+      
+        echo "##[info] Deploying commit ${{ env.SHA }} to target branches."
         latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
         TAG_MESSAGE=$(git tag -l --format='%(contents)' $latest_tag)
         echo "##[info] Latest Tag = $TAG_MESSAGE"
@@ -121,14 +127,14 @@ jobs:
           git fetch
           git checkout $target_branch
 
-          echo "##[info]# Populating target directory${{ env.DIRECTORY }} on $target_branch branch to mirror ${{ env.SHA_BRANCH }}"
+          echo "##[info] Populating target directory${{ env.DIRECTORY }} on $target_branch branch to mirror ${{ env.SHA_BRANCH }}"
           rsync -av --delete /tmp/temp-dir/ ${{ github.workspace }}/${{ env.DIRECTORY }}/
 
-          echo "##[info]# Committing and pushing changes to target branch $target_branch"
+          echo "##[info] Committing and pushing changes to target branch $target_branch"
           git add -A
           if ! git diff --quiet; then
               COMMIT_MSG="Migrating changes from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag: $TAG_MESSAGE [skip ci]"
-              echo "##[info] $COMMIT_MSG"
+              echo "##[debug] $COMMIT_MSG"
               git add -A
               git commit -m "$COMMIT_MSG"
               git push origin $target_branch
@@ -137,7 +143,7 @@ jobs:
               if git diff --staged --quiet; then
           fi  
 
-          echo "##[info]# Updating Deployment Status to Success for commit SHA ${{ env.SHA }}"
+          echo "##[info] Updating Deployment Status to Success for commit SHA ${{ env.SHA }}"
           CMD="curl -X POST -H \"Authorization: Bearer ${{ secrets.AUTH }}\" -H \"Accept: application/vnd.github.v3+json\" "
           CMD+="https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.SHA }} "
           CMD+="-d '{\"state\": \"success\", \"description\": \"Deploying SHA ${{ env.SHA }} from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag. "
@@ -145,7 +151,7 @@ jobs:
           echo "##[info] Command: $CMD"
 
           RESPONSE=$(eval "${CMD}")
-          echo "##[info]# API Response: $RESPONSE"
+          echo "##[info] API Response: $RESPONSE"
 
           desc="Deploying SHA ${{ env.SHA }} from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag. "
           desc+="New code in ${{ env.DIRECTORY }} directory on both branches."
@@ -155,19 +161,19 @@ jobs:
           CMD+="-f description='${desc}'"
           eval "${CMD}"
         done
-      env:
-        GH_TOKEN: ${{ secrets.AUTH }}
 
     - name: Remove Lock File
       run: |
+      
         git fetch origin ${{ env.SHA_BRANCH }}
         git checkout ${{ env.SHA_BRANCH }}
 
+        echo "##[debug] Resetting config for new branch"
         git config user.name "CodeApprover"
         git config user.email "pucfada@pm.me"
 
         msg="Removed lock file to deploy SHA ${{ env.SHA }} [skip ci]"
-        echo "##[info]# $msg"
+        echo "##[debug] Commit Message: $msg"
 
         git rm "$lock_file"
         git commit -m "$msg"
@@ -176,15 +182,16 @@ jobs:
     - name: Trigger Next Workflow
       if: success()
       run: |
-        CMD="curl -L -X POST "
-        CMD+="-H \"Accept: application/vnd.github+json\" "
-        CMD+="-H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
-        CMD+="-H \"X-GitHub-Api-Version: 2022-11-28\" "
-        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
-        CMD+="-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\","
-        CMD+="\"client_payload\":{"
-        CMD+="\"sha\":\"${{ github.sha }}\","
-        CMD+="\"csproj\":\"${{ env.CSPROJ }}\"}'"
+      
+        CMD=$(echo "curl -L -X POST" \
+        "-H \"Accept: application/vnd.github+json\"" \
+        "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+        "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+        "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+        "-d '{\"event_type\":\"$trigger\"," \
+        "\"client_payload\":{" \
+        "\"sha\":\"${{ env.SHA }}\"," \
+        "\"csproj\":\"${{ env.CSPROJ }}\"}'")
 
         retries=0
         while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
@@ -198,7 +205,7 @@ jobs:
                     sleep ${{ vars.WAIT_SECONDS }}
                 else
                     echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                    echo "##[error] Failed to trigger ${env.NEXT_WORKFLOW} workflow with CURL command: $CMD." && exit 90
+                    echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
                 fi
             else
                 break # successful curl
