Update 04-01-versioning.yml[skipci]

diff --git a/.github/workflows/04-01-versioning.yml b/.github/workflows/04-01-versioning.yml
--- a/.github/workflows/04-01-versioning.yml
+++ b/.github/workflows/04-01-versioning.yml
@@ -87,38 +87,38 @@ jobs:
           echo "##[debug] New version number = $new_version"
           echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
 
-          - name: Trigger Next Workflow
-          if: success()
-          run: |
+      - name: Trigger Next Workflow
+        if: success()
+        run: |
  
-            CMD=$(echo "curl -L -X POST" \
-            "-H \"Accept: application/vnd.github+json\"" \
-            "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
-            "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
-            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
-            "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
-            "\"client_payload\":{" \
-            "\"sha\":\"${{ env.SHA }}\"," \
-            "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
-            "\"new_version\":\"${{ env.NEW_VERSION }}\"," \
-            "\"csproj\":\"${{ env.CSPROJ }}\"}'")
+          CMD=$(echo "curl -L -X POST" \
+          "-H \"Accept: application/vnd.github+json\"" \
+          "-H \"Authorization: Bearer ${{ secrets.AUTH }}\"" \
+          "-H \"X-GitHub-Api-Version: 2022-11-28\"" \
+          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
+          "-d '{\"event_type\":\"${{ env.NEXT_WORKFLOW }}\"," \
+          "\"client_payload\":{" \
+          "\"sha\":\"${{ env.SHA }}\"," \
+          "\"sha_branch\":\"${{ env.SHA_BRANCH }}\"," \
+          "\"new_version\":\"${{ env.NEW_VERSION }}\"," \
+          "\"csproj\":\"${{ env.CSPROJ }}\"}'")
 
-            retries=0
-            while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
-                eval "$CMD"
-                CURL_EXIT_CODE=$?
-                if [[ $CURL_EXIT_CODE -ne 0 ]]; then
-                    echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
-                    retries=$((retries+1))
-                    if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
-                        echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
-                        sleep ${{ vars.WAIT_SECONDS }}
-                    else
-                        echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
-                        echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
-                    fi
-                else
-                    break # successful curl
-                fi
-            done
-            echo "##[debug] CURL command: $CMD"
+          retries=0
+          while [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; do
+              eval "$CMD"
+              CURL_EXIT_CODE=$?
+              if [[ $CURL_EXIT_CODE -ne 0 ]]; then
+                  echo "##[error] Curl command failed on attempt $((retries+1)) with exit code $CURL_EXIT_CODE"
+                  retries=$((retries+1))
+                  if [[ $retries -lt ${{ vars.MAX_RETRIES }} ]]; then
+                      echo "##[warn] Retrying in ${{ vars.WAIT_SECONDS }} seconds..."
+                      sleep ${{ vars.WAIT_SECONDS }}
+                  else
+                      echo "##[error] Exhausted ${{ vars.MAX_RETRIES }} retries at ${{ vars.WAIT_SECONDS }} intervals."
+                      echo "##[error] Failed to trigger ${{ env.NEXT_WORKFLOW }} workflow with CURL command: $CMD." && exit 90
+                  fi
+              else
+                  break # successful curl
+              fi
+          done
+          echo "##[debug] CURL command: $CMD"
