Update 04-03-deploy-git.yml[skip ci]

diff --git a/.github/workflows/04-03-deploy-git.yml b/.github/workflows/04-03-deploy-git.yml
--- a/.github/workflows/04-03-deploy-git.yml
+++ b/.github/workflows/04-03-deploy-git.yml
@@ -99,74 +99,85 @@ jobs:
         echo "deploy_branches=${deploy_branches[@]}" >> $GITHUB_ENV
         echo "directory=$directory" >> $GITHUB_ENV
 
+    - name: Reset all branches to mirror main if push is to main
+      run: |
+      
+        if [[ "${{ env.SHA_BRANCH }}" == "main" ]]; then
+            for target_branch in code-development code-staging code-production; do
+                git fetch origin
+                git checkout $target_branch
+                git reset --hard ${{ env.SHA }}
+                git push origin $target_branch --force
+            done
+        fi
+
     - name: Set and Copy Source Directory to Temp Dir
       run: |
       
-        src_dir=${{ env.SHA_BRANCH }}
-        src_dir=${src_dir#code-}
-        dir_path=$(find ${{ github.workspace }} -type d -name "$src_dir" -print | head -n 1)
-
-        if [[ ! -d "$dir_path" ]] || [[ ! $(ls -A "$dir_path") ]]; then
-          echo "##[error] Source directory does not exist or is empty" && exit 44
-        fi
-
-        rsync -av --delete $dir_path/ /tmp/temp-dir/
+         src_dir=${{ env.SHA_BRANCH }}
+         src_dir=${src_dir#code-}
+         dir_path=$(find ${{ github.workspace }} -type d -name "$src_dir" -print | head -n 1)
+    
+         if [[ ! -d "$dir_path" ]] || [[ ! $(ls -A "$dir_path") ]]; then
+           echo "##[error] Source directory does not exist or is empty" && exit 44
+         fi
+    
+         rsync -av --delete $dir_path/ /tmp/temp-dir/
 
     - name: Deploy to Target Branches
       run: |
       
-        echo "##[info] Deploying commit ${{ env.SHA }} to target branches."
-        latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
-        TAG_MESSAGE=$(git tag -l --format='%(contents)' $latest_tag)
-        echo "##[info] Latest Tag = $TAG_MESSAGE"
+         if [[ "${{ env.SHA_BRANCH }}" != "main" ]]; then
+             echo "##[info] Deploying commit ${{ env.SHA }} to target branches."
+             latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
+             TAG_MESSAGE=$(git tag -l --format='%(contents)' $latest_tag)
+             echo "##[info] Latest Tag = $TAG_MESSAGE"
+        
+             for target_branch in code-development code-staging code-production; do
+                 [[ $target_branch == "${{ env.SHA_BRANCH }}" ]] && continue
+                 
+                 git fetch origin
+                 git checkout $target_branch
+                 rsync -av --delete /tmp/temp-dir/ ${{ github.workspace }}/${{ env.DIRECTORY }}/
+                 git add -A
+                 
+                 if ! git diff --quiet; then
+                     COMMIT_MSG="Migrating changes from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag: $TAG_MESSAGE [skip ci]"
+                     echo "##[debug] $COMMIT_MSG"
+                     git commit -m "$COMMIT_MSG"
+                     git push origin $target_branch
+                 else
+                     echo "##[error] No changes detected. Skipping commit for $target_branch [skip ci]"
+                 fi  
+             done
+         fi
 
-        for target_branch in code-development code-staging code-production; do
-          [[ $target_branch == "${{ env.SHA_BRANCH }}" ]] && continue
-          
-          git fetch --all
-          git checkout $target_branch
-
-          echo "##[info] Populating target directory${{ env.DIRECTORY }} on $target_branch branch to mirror ${{ env.SHA_BRANCH }}"
-          rsync -av --delete /tmp/temp-dir/ ${{ github.workspace }}/${{ env.DIRECTORY }}/
-
-          echo "##[info] Committing and pushing changes to target branch $target_branch"
-          git add -A
-          if ! git diff --quiet; then
-              COMMIT_MSG="Migrating changes from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag: $TAG_MESSAGE [skip ci]"
-              echo "##[debug] $COMMIT_MSG"
-              git add -A
-              git commit -m "$COMMIT_MSG"
-              git push origin $target_branch
-          else
-              echo "##[error] No changes detected. Skipping commit for $target_branch [skip ci]" && exit 45
-          fi  
-
-          echo "##[info] Updating Deployment Status to Success for commit SHA ${{ env.SHA }}"
-          CMD=$(echo "curl -L -X POST" \
-            "-H 'Authorization: Bearer ${{ secrets.AUTH }}'" \
-            "-H 'Accept: application/vnd.github.v3+json'" \
-            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.SHA }}" \
-            "-d '{\"state\": \"success\"," \
-            "\"description\": \"Deploying SHA ${{ env.SHA }} from ${{ env.SHA_BRANCH }} " \
-            "to $target_branch based on tag $latest_tag." \
-            " New code in ${{ env.DIRECTORY }} directory on both branches.\"," \
-            "\"context\": \"deployment\"}'")
-          echo "##[debug] Command: $CMD"
-
-          RESPONSE=$(eval "$CMD")
-          echo "##[debug] API Response: $RESPONSE"
-
-          desc="Deploying SHA ${{ env.SHA }} from ${{ env.SHA_BRANCH }} to $target_branch based on tag $latest_tag. "
-          desc+="New code in ${{ env.DIRECTORY }} directory on both branches."
-          
-          CMD=$(echo "gh api --method POST" \
-            "-H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28'" \
-            "/repos/${{ github.repository }}/deployments" \
-            "-f ref='${{ env.SHA_BRANCH }}'" \
-            "-f payload='{\"action\": \"deploy\", \"target_branch\": \"$target_branch\"}'" \
-            "-f description='$desc'")
-          eval "$CMD"
-        done
+    - name: Update Deployment Status
+      run: |
+      
+         latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
+         desc="Deploying SHA ${{ env.SHA }} from ${{ env.SHA_BRANCH }} based on tag $latest_tag."
+         
+         CMD_STATUS=$(echo "curl -L -X POST" \
+                      "-H 'Authorization: Bearer ${{ secrets.AUTH }}'" \
+                      "-H 'Accept: application/vnd.github.v3+json'" \
+                      "https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.SHA }}" \
+                      "-d '{\"state\": \"success\"," \
+                      "\"description\": \"$desc\"," \
+                      "\"context\": \"deployment/${{ env.SHA_BRANCH }}\"}'")
+         
+         RESPONSE_STATUS=$(eval "$CMD_STATUS")
+         echo "##[debug] Status API Response: $RESPONSE_STATUS"
+         
+         CMD_DEPLOY=$(echo "gh api --method POST" \
+                      "-H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28'" \
+                      "/repos/${{ github.repository }}/deployments" \
+                      "-f ref='${{ env.SHA_BRANCH }}'" \
+                      "-f payload='{\"action\": \"deploy\", \"target_branch\": \"${{ env.SHA_BRANCH }}\"}'" \
+                      "-f description='$desc'")
+         
+         RESPONSE_DEPLOY=$(eval "$CMD_DEPLOY")
+         echo "##[debug] Deployment API Response: $RESPONSE_DEPLOY"
 
     - name: Trigger Next Workflow
       if: success()
