Update 04-lockfile-checker.yml

diff --git a/.github/workflows/04-lockfile-checker.yml b/.github/workflows/04-lockfile-checker.yml
--- a/.github/workflows/04-lockfile-checker.yml
+++ b/.github/workflows/04-lockfile-checker.yml
@@ -4,10 +4,12 @@ name: "Check Lock File"
 # Workflow to manage lock files for sequential task execution within a branch.
 
 # Exit Codes
-# 30 - SHA checkout failure.
 # 36 - Failed to push lock file.
 # 37 - Failed to fetch SAH branch.
-# 38 - Failed to detect pushed lock file.
+# 38 - Lock file presence persists.
+# 39 - Failed to push lock file.
+# 40 - Failed to fetch new remote.
+# 41 - Failed to detect pushed lock file.
 
 on:
   repository_dispatch:
@@ -17,8 +19,6 @@ env:
   SHA: ${{ github.event.client_payload.sha }}
   BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
-  MAX_RETRIES: ${{ secrets.MAX_RETRIES }}
-  SLEEP_MINUTES: ${{ secrets.SLEEP_MINUTES }}
 
 jobs:
 
@@ -37,11 +37,6 @@ jobs:
         ref: ${{ env.SHA }}
         fetch-depth: 0
 
-    - name: Configure Git User and Email
-      run: |
-        git config user.name "CodeApprover"
-        git config user.email "pucfada@pm.me"
-
     - name: Set Lock File Name Based on Branch
       run: |
         branch=${{ env.BRANCH_NAME }}
@@ -52,47 +47,60 @@ jobs:
             echo "LOCK_FILE=.main.lock" >> $GITHUB_ENV
         fi
 
-    - name: Check Lock File with Retry
+    - name: Check for Remote Lock File
       run: |
-        for (( i=1; i<=${{ env.MAX_RETRIES }}; i++ )); do
-            git fetch origin ${{ env.BRANCH_NAME }}
-            git checkout ${{ env.BRANCH_NAME }}
-            if [ $? -ne 0 ]; then
-                echo "##[error] Failed to checkout ${{ env.BRANCH_NAME }}"
-                exit 30
-        fi
+        retries=0
+        while [[ $retries -lt ${{ secrets.MAX_RETRIES }} ]]; do
+          git fetch origin ${{ env.BRANCH_NAME }}
+          git checkout ${{ env.BRANCH_NAME }}
+          
+          commits_before_sha=$(git rev-list ${{ env.SHA }}~1..${{ env.BRANCH_NAME }} --)
+          
+          # Check for lock file
+          if git ls-tree -r $commits_before_sha | grep "${{ env.LOCK_FILE }}"; then
+              retries=$((retries+1))
+              locked_sha=$(cat "${{ env.LOCK_FILE }}")
+              echo "##[warn] Lock file ${{ env.LOCK_FILE }} found for commit SHA $locked_sha."
+              echo "##[warn] Waiting ${{ secrets.WAIT_MINUTES }} minutes before retry $retries of ${{ secrets.MAX_TRIES }}."
+              sleep $((${{ secrets.WAIT_MINUTES }} * 60))
+          else
+              echo "##[info] Lock file ${{ env.LOCK_FILE }} check passed - continuing."
+              break
+          fi
 
-        commits_before_sha=$(git rev-list ${{ env.SHA }}~1..${{ env.BRANCH_NAME }} --)
-
-        if git ls-tree -r $commits_before_sha | grep "${{ env.LOCK_FILE }}"; then
-            echo "Lock file found. Waiting ${{ env.SLEEP_MINUTES }} minutes before retrying."
-            sleep $((${{ env.SLEEP_MINUTES }} * 60))
-        else
-            break
-        fi
-        echo "::endgroup::"
+          # Exit loop if at max retries
+          if [[ $retries -eq ${{ env.MAX_RETRIES }} ]]; then
+            echo "##[error] Reached (${{ secrets.MAX_RETRIES }}) max retries at ${{ secrets.WAIT_MINUTES }} intervals."
+            echo "##[error] Lock file ${ env.LOCK_FILE }} presence presists."
+            exit 38
+          fi
         done
+
+    - name: Set Lock file
+      run: |
+        git config user.name "CodeApprover"
+        git config user.email "pucfada@pm.me"
 
         echo "${{ env.SHA }}" > "${{ env.LOCK_FILE }}"
         git add "${{ env.LOCK_FILE }}"
         git commit -m "Adding ${{ env.LOCK_FILE }} for ${{ env.SHA }} [skip ci]."
 
         if ! git push origin HEAD:${{ env.BRANCH_NAME }}; then
-        echo "::error::Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}"
-        exit 36
+        echo "##[[error] Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}"
+        exit 39
         fi
 
         git fetch origin ${{ env.BRANCH_NAME }}
         if [ $? -ne 0 ]; then
-        echo "::error::Failed to fetch ${{ env.BRANCH_NAME }}"
-        exit 37
+        echo "##[[error] Failed to fetch ${{ env.BRANCH_NAME }}"
+        exit 40
         fi
 
         if ! git ls-tree HEAD -- ${{ env.LOCK_FILE }}; then
-        echo "::error::Lock file ${{ env.LOCK_FILE }} was not detected remotely."
-        exit 38
+        echo "##[error] Lock file ${{ env.LOCK_FILE }} was not detected remotely."
+        exit 41
         else
-        echo "Lock file ${{ env.LOCK_FILE }} successfully created and pushed."
+        echo "##[info] Lock file ${{ env.LOCK_FILE }} successfully created and pushed."
         fi
 
     - name: Trigger Next Workflow # 05-codeql-analysis.yml | development 07-versioning.yml
