Update 04-lockfile-checker.yml

diff --git a/.github/workflows/04-lockfile-checker.yml b/.github/workflows/04-lockfile-checker.yml
--- a/.github/workflows/04-lockfile-checker.yml
+++ b/.github/workflows/04-lockfile-checker.yml
@@ -17,7 +17,7 @@ on:
 
 env:
   SHA: ${{ github.event.client_payload.sha }}
-  BRANCH_NAME: ${{ github.event.client_payload.branch_name }}
+  SHA_BRANCH: ${{ github.event.client_payload.sha_branch }}
   CSPROJ: ${{ github.event.client_payload.csproj }}
 
 jobs:
@@ -39,7 +39,7 @@ jobs:
 
     - name: Set Lock File Name Based on Branch
       run: |
-        branch=${{ env.BRANCH_NAME }}
+        branch=${{ env.SHA_BRANCH }}
         if [[ $branch == "code-"* ]]; then
             lock_name=${branch#code-}
             echo "LOCK_FILE=.$lock_name.lock" >> $GITHUB_ENV
@@ -51,10 +51,10 @@ jobs:
       run: |
         retries=0
         while [[ $retries -lt ${{ secrets.MAX_RETRIES }} ]]; do
-          git fetch origin ${{ env.BRANCH_NAME }}
-          git checkout ${{ env.BRANCH_NAME }}
+          git fetch origin ${{ env.SHA_BRANCH }}
+          git checkout ${{ env.SHA_BRANCH }}
           
-          commits_before_sha=$(git rev-list ${{ env.SHA }}~1..${{ env.BRANCH_NAME }} --)
+          commits_before_sha=$(git rev-list ${{ env.SHA }}~1..${{ env.SHA_BRANCH }} --)
           
           # Check for lock file
           if git ls-tree -r $commits_before_sha | grep "${{ env.LOCK_FILE }}"; then
@@ -85,14 +85,14 @@ jobs:
         git add "${{ env.LOCK_FILE }}"
         git commit -m "Adding ${{ env.LOCK_FILE }} for ${{ env.SHA }} [skip ci]."
 
-        if ! git push origin HEAD:${{ env.BRANCH_NAME }}; then
-        echo "##[[error] Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}"
+        if ! git push origin HEAD:${{ env.SHA_BRANCH }}; then
+        echo "##[error] Failed to push ${{ env.LOCK_FILE }} for ${{ env.SHA }}"
         exit 39
         fi
 
-        git fetch origin ${{ env.BRANCH_NAME }}
+        git fetch origin ${{ env.SHA_BRANCH }}
         if [ $? -ne 0 ]; then
-        echo "##[[error] Failed to fetch ${{ env.BRANCH_NAME }}"
+        echo "##[error] Failed to fetch ${{ env.SHA_BRANCH }}"
         exit 40
         fi
 
@@ -115,7 +115,7 @@ jobs:
         BASE="{\"event_type\": \"$trigger\", \"client_payload\": {"
         SHA="\"sha\": \"${{ env.SHA }}\","
         CSPROJ="\"csproj\": \"${{ env.CSPROJ }}\","
-        BRANCH="\"branch_name\": \"${{ env.SHA_BRANCH }}\""
+        BRANCH="\"sha_branch\": \"${{ env.SHA_BRANCH }}\""
         END="}}"
 
         curl -s -o /dev/null -X POST \
