Update 10-development-success.yml

diff --git a/.github/workflows/10-development-success.yml b/.github/workflows/10-development-success.yml
--- a/.github/workflows/10-development-success.yml
+++ b/.github/workflows/10-development-success.yml
@@ -47,8 +47,10 @@ jobs:
       - name: Check Current Deployment Status
         run: |
           CHECK_STATUS_CMD="curl -s -H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
-          CHECK_STATUS_CMD+="https://api.github.com/repos/${{ github.repository }}/deployments/sha:${{ env.SHA }}/statuses/latest"
-          CURRENT_STATUS=$(eval "${CHECK_STATUS_CMD}")
+          CHECK_STATUS_CMD+="https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.SHA }}"
+          CURRENT_STATUS=$(eval "${CHECK_STATUS_CMD}" | grep -oP '(?<=state": ")[^"]*')
+          echo "##[info]# Current Deployment Status is '$CURRENT_STATUS'"
+          echo "CURRENT_STATUS=$CURRENT_STATUS" >> $GITHUB_ENV
           if [[ $CURRENT_STATUS == *"Not Found"* ]]; then
             echo "##[info]# Current Deployment Status not found. This might be expected for a new deployment."
             CURRENT_STATUS="Unset"
@@ -69,20 +71,16 @@ jobs:
       - name: Check Updated Deployment Status
         run: |
           CHECK_STATUS_CMD="curl -s -H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
-          CHECK_STATUS_CMD+="https://api.github.com/repos/${{ github.repository }}/deployments/sha:${{ env.SHA }}/statuses/latest"
-          UPDATED_STATUS=$(eval "${CHECK_STATUS_CMD}")
+          CHECK_STATUS_CMD+="https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.SHA }}"
+          UPDATED_STATUS=$(eval "${CHECK_STATUS_CMD}" | grep -oP '(?<=state": ")[^"]*')
           echo "##[info]# Updated Deployment Status is '$UPDATED_STATUS'"
           echo "UPDATED_STATUS=$UPDATED_STATUS" >> $GITHUB_ENV
 
       - name: Verify Deployment Status Update
         run: |
-          if [[ -z "${{ env.UPDATED_STATUS }}" ]]; then
-              echo "##[error]# Updated status is not properly populated --> Exit 50"
-              exit 50
-          fi
           if [[ "${{ env.UPDATED_STATUS }}" != "${{ env.CURRENT_STATUS }}" ]]; then
-              echo "##[error]# Deployment status was not updated correctly --> Exit 51"
-              exit 51
+              echo "##[error]# Deployment status was not updated correctly --> Exit 50"
+              exit 50
           else
               echo "##[info]# Deployment status updated successfully."
           fi
