Update codeql.yml
Testing codeql

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -60,35 +60,38 @@ jobs:
     # Save the CodeQL results zip to the repository
     - name: Save CodeQL results
       id: save_results
-      run: |    
-        # Determine the correct source zip file based on the matrix language
-        case ${{ matrix.language }} in
-          csharp)
-            source_zip="/home/runner/work/_temp/codeql_databases/csharp.zip"
-            ;;
-          javascript)
-            source_zip="/home/runner/work/_temp/codeql_databases/javascript.zip"
-            ;;
-          typescript)
-            source_zip="/home/runner/work/_temp/codeql_databases/typescript.zip"
-            ;;
-          *)
-            echo "Invalid language: ${{ matrix.language }}"
-            exit 1
-            ;;
-        esac
-  
-        # Move the source_zip file to the repository's results/codeql directory
+      run: |  
         mkdir -p ./results/codeql
-        cp "$source_zip" ./results/codeql/
-        
-        # Set the personal access token as an environment variable for git
         export GH_TOKEN="${{ secrets.TOKEN }}"
         
         git config --global user.email "github-actions@github.com"
         git config --global user.name "GitHub Actions"
         git config --global user.login "${{ secrets.LOGIN }}"
-        
-        git add ./results/codeql/
-        git commit -m "Add CodeQL results for ${{ matrix.language }} [skip ci]"  # Skip workflow runs
+
+        # Save based on matrix language
+        case ${{ matrix.language }} in
+          csharp)
+            source_zip="/home/runner/work/_temp/codeql_databases/csharp.zip"
+            cp $source_zip ./results/codeql/
+            git add ./results/codeql/csharp.zip
+            git commit -m "Add CodeQL results for ${{ matrix.language }} [skip ci]"  # Skip workflow runs
+            ;;
+          javascript)
+            source_zip="/home/runner/work/_temp/codeql_databases/javascript.zip"
+            cp $source_zip ./results/codeql/
+            git add ./results/codeql/javascript.zip
+            git commit -m "Add CodeQL results for ${{ matrix.language }} [skip ci]"  # Skip workflow runs
+            ;;
+          typescript)
+            source_zip="/home/runner/work/_temp/codeql_databases/typescript.zip"
+            cp $source_zip ./results/codeql/
+            git add ./results/codeql/typescript.zip
+            git commit -m "Add CodeQL results for ${{ matrix.language }} [skip ci]"  # Skip workflow runs
+            ;;
+          *)
+            echo "Invalid language: ${{ matrix.language }}"
+            exit 1
+            ;;
+        esac   
+
         git push origin main
