Update codeql.yml
Testing with one language

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -1,14 +1,3 @@
-# For most projects, this workflow file will not need changing; you simply need
-# to commit it to your repository.
-#
-# You may wish to alter this file to override the set of languages analyzed,
-# or to provide custom queries or build logic.
-#
-# ******** NOTE ********
-# We have attempted to detect the languages in your repository. Please check
-# the `language` matrix defined below to confirm you have the correct set of
-# supported CodeQL languages.
-#
 name: "CodeQL"
 
 on:
@@ -23,11 +12,6 @@ on:
 jobs:
   analyze:
     name: Analyze
-    # Runner size impacts CodeQL analysis time. To learn more, please see:
-    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
-    #   - https://gh.io/supported-runners-and-hardware-resources
-    #   - https://gh.io/using-larger-runners
-    # Consider using larger runners for possible analysis time improvements.
     runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
     timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
     permissions:
@@ -38,11 +22,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        language: [ 'csharp', 'javascript' ]
+        language: [ 'csharp' ]
         # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby', 'swift' ]
-        # Use only 'java' to analyze code written in Java, Kotlin or both
-        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
-        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
 
     steps:
     - name: Checkout repository
@@ -53,13 +34,6 @@ jobs:
       uses: github/codeql-action/init@v2
       with:
         languages: ${{ matrix.language }}
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
-
-        # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
-
 
     # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
     # If this step fails, then you should remove it and run the build manually (see below)
@@ -80,3 +54,38 @@ jobs:
       uses: github/codeql-action/analyze@v2
       with:
         category: "/language:${{matrix.language}}"
+
+   # Save the CodeQL results zip to the repository
+    - name: Save CodeQL results
+      run: |    
+        # Determine the correct source zip file based on the matrix language
+        case ${{ matrix.language }} in
+          csharp)
+            source_zip="/home/runner/work/_temp/codeql_databases/csharp.zip"
+            ;;
+          javascript)
+            source_zip="/home/runner/work/_temp/codeql_databases/javascript.zip"
+            ;;
+          typescript)
+            source_zip="/home/runner/work/_temp/codeql_databases/typescript.zip"
+            ;;
+          *)
+            echo "Invalid language: ${{ matrix.language }}"
+            exit 1
+            ;;
+        esac
+  
+        # Move the source_zip file to the repository's results/codeql directory
+        mkdir -p ./results/codeql
+        cp "$source_zip" ./results/codeql/
+        
+        # Set the personal access token as an environment variable for git
+        export GH_TOKEN="${{ secrets.TOKEN }}"
+        
+        git config --global user.email "github-actions@github.com"
+        git config --global user.name "GitHub Actions"
+        git config --global user.login "${{ secrets.LOGIN }}"
+        
+        git add ./results/codeql/
+        git commit -m "Add CodeQL results for ${{ matrix.language }} [skip ci]"  # Skip workflow runs
+        git push origin main
