Update deploy-git.yml

diff --git a/.github/workflows/deploy-git.yml b/.github/workflows/deploy-git.yml
--- a/.github/workflows/deploy-git.yml
+++ b/.github/workflows/deploy-git.yml
@@ -100,19 +100,27 @@ jobs:
         git fetch origin ${{ env.BRANCH_NAME }}
         lock_found=0
         
-        # Find a lock file
-        if git ls-tree -r HEAD --full-tree | grep "${{ env.LOCK_FILE }}"; then
-            lock_found=1
-            echo "Lock file ${{ env.LOCK_FILE }} found in branch ${{ env.BRANCH_NAME }}"
+        # Get the commit SHA of the latest lock file creation with lock file name, the payload SHA and [skip ci] in the message
+        commit_sha=$(git log --grep="Adding ${{ env.LOCK_FILE }} file for ${{ github.event.client_payload.sha }} [skip ci]" -n 1 | awk '{print $1}')
+        
+        if [ ! -z "$commit_sha" ]; then
+            if git show "$commit_sha" | grep "${{ env.LOCK_FILE }}"; then
+                lock_found=1
+                echo "Lock file ${{ env.LOCK_FILE }} found in commit $commit_sha on branch ${{ env.BRANCH_NAME }}"
+            fi
         fi
 
-        # Delete lock file if it exists
+        # Delete lock file for payload sha
         if [[ "$lock_found" -eq 1 ]]; then
           trap 'echo "Error on line $LINENO: $BASH_COMMAND"; exit 1' ERR
           git pull origin "${{ env.BRANCH_NAME }}"
           git rm "${{ env.LOCK_FILE }}"
           git commit -m "Remove lock after versioning"
           git push origin "${{ env.BRANCH_NAME }}"
+        else
+          # Fail if a lock file does not exist
+          echo "Required lock file for $ {{ env.SHA }} was not found - exiting."
+          exit 1
         fi
 
     - name: Create GitHub Deployment
