Update linter.yml

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,3 +1,4 @@
+---
 name: "Linter"
 
 on:
@@ -8,12 +9,12 @@ jobs:
   ##############################################################################################################
   # Report usage
   ##############################################################################################################
-  report-usage:
+  Report:
     runs-on: ubuntu-latest
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }}"
-      - run: echo "🐧 CodeQL is running on a ${{ runner.os }} server hosted by GitHub Actions."
-      - run: echo "🔎 Branch name is ${{ github.ref }}. Repository is ${{ github.repository }}"
+      - run: echo "🎉 Job triggered by a ${{ github.event_name }}"
+      - run: echo "🐧 Running ${{ runner.os }} server on GitHub Actions."
+      - run: echo "🔎 Branch ${{ github.ref }}. Repository ${{ github.repository }}"
 
   ##############################################################################################################
   # Run CodeQL Linter - https://github.com/github/codeql.
@@ -24,7 +25,7 @@ jobs:
   ##############################################################################################################
   analyze:
     name: Analyze
-    needs: report-usage
+    needs: Report
     runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
     timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
     permissions:
@@ -66,10 +67,21 @@ jobs:
           VALIDATE_ALL_CODEBASE: false
           DEFAULT_BRANCH: ${{ github.ref }}
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
+  
+################################################################################################################
+# Clear nuget package cache for clean install
+################################################################################################################
+  clean-up:
+    name: Clean up Nuget
+    needs: super-linter
+    runs-on: ubuntu-latest
+    steps:
+      - name: clean-up-nuget-cache
+        run: dotnet nuget locals all --clear  
 
-  ##############################################################################################################
-  # Run StyleCop Linting - https://github.com/StyleCop/StyleCop
-  ##############################################################################################################
+##############################################################################################################
+# Run StyleCop Linting - https://github.com/StyleCop/StyleCop
+##############################################################################################################
   stylecop-linting:
     runs-on: ubuntu-latest
     needs: super-linter
@@ -81,8 +93,17 @@ jobs:
         with:
           dotnet-version: 7.0.x
       - name: Restore dependencies
-        run: dotnet restore
+        run: dotnet restore --no-cache
       - name: Install StyleCop.MSBuild
         run: dotnet add package StyleCop.MSBuild --version 6.2.0
       - name: Run StyleCop analysis
-        run: dotnet build /p:StyleCopEnabled=true
+        run: |
+          # Find the project file (Blazor SqlLite Golf Club.csproj) in the repository
+          project_file=$(find "${{ github.workspace }}" -type f -name "Blazor SqlLite Golf Club.csproj" -print -quit)
+          # Ensure the project file exists before running StyleCop
+          if [ -f "$project_file" ]; then
+            dotnet build "$project_file" /p:StyleCopEnabled=true
+          else
+            echo "Project file not found: Blazor SqlLite Golf Club.csproj"
+            exit 1
+          fi
