Update linter-stylecop.yml [skip ci]

diff --git a/.github/workflows/linter-stylecop.yml b/.github/workflows/linter-stylecop.yml
--- a/.github/workflows/linter-stylecop.yml
+++ b/.github/workflows/linter-stylecop.yml
@@ -12,17 +12,9 @@ env:
 
 jobs:
 
-  stylecop-linting:
-    name: StyleCop Linting
+  setup:
+    name: Setup Repository
     runs-on: ubuntu-latest
-    timeout-minutes: 15
-
-    if: >
-      github.ref == 'refs/heads/code-development' ||
-      github.ref == 'refs/heads/code-staging' ||
-      github.ref == 'refs/heads/code-production' ||
-      github.ref == 'refs/heads/main'
-
     steps:
     
     - name: Log Timestamp
@@ -36,9 +28,6 @@ jobs:
       uses: actions/checkout@v3.5.3
       with:
         ref: ${{ env.SHA }}
-
-    - name: Fetch all branches
-      run: git fetch --all
 
     - name: Extract Branch Name from SHA Commit
       run: |
@@ -54,6 +43,12 @@ jobs:
         CSPROJ=$(find "${{ github.workspace }}/$(echo "${{ env.BRANCH_NAME }}" | sed 's/^code-//')" -name "${{ env.PROJ_NAME }}.csproj")
         [[ -z "$CSPROJ" ]] && echo "Error: .csproj file not found." && exit 1 || echo "CSPROJ=$CSPROJ" >> $GITHUB_ENV
 
+  linting:
+    name: StyleCop Linting
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+
     - name: Setup .NET environment
       uses: actions/setup-dotnet@v3.2.0
       with:
@@ -63,10 +58,33 @@ jobs:
       run: |
         dotnet restore --no-cache "$CSPROJ"
 
-    - name: Dotnet Build
+    - name: Dotnet Build with StyleCop
       run: |
         CMD="dotnet build --no-restore \"$CSPROJ\""
         CMD+=" /p:StyleCopEnabled=true"
         CMD+=" /p:StyleCopTreatErrorsAsWarnings=false"
         CMD+=" /p:StyleCopForceFullAnalysis=false"
         eval "$CMD"
+
+  trigger-tests:
+    name: Trigger Environment-Specific Tests
+    runs-on: ubuntu-latest
+    needs: linting
+    steps:
+
+    - name: Trigger Appropriate Workflow
+      if: success()
+      run: |
+        ENV_NAME=$(echo "${{ env.BRANCH_NAME }}" | sed 's/^code-//')
+        case $ENV_NAME in
+          development) EVENT_TYPE="trigger-development-tests" ;;
+          staging) EVENT_TYPE="trigger-env-staging-tests" ;;
+          production) EVENT_TYPE="trigger-production-tests" ;;
+          *) echo "Error: Unexpected environment name"; exit 1 ;;
+        esac
+        CMD="curl -X POST -H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
+        CMD+="-H \"Accept: application/vnd.github.v3+json\" "
+        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
+        CMD+="-d '{\"event_type\": \"$EVENT_TYPE\", "
+        CMD+="\"client_payload\": {\"sha\": \"${{ github.sha }}\"}}'"
+        eval ${CMD}
