Update test-success.yml

diff --git a/.github/workflows/test-success.yml b/.github/workflows/test-success.yml
--- a/.github/workflows/test-success.yml
+++ b/.github/workflows/test-success.yml
@@ -3,7 +3,10 @@ name: Test Success
 
 on:
   repository_dispatch:
-    types: "trigger-test-success"
+    types: trigger-test-success
+
+env:
+  DOCKER_REPO: blazor-sqlite-devops
 
 jobs:
 
@@ -27,17 +30,24 @@ jobs:
         ref: ${{ env.SHA }}
         fetch-depth: 0 # Fetch all
 
-    - name: Set Branch Name and Environment
+    - name: Extract Branch Name from SHA Commit
       run: |
-        ref=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')
-        echo "BRANCH_NAME=$ref" >> $GITHUB_ENV
+        branch=$(git branch -r --contains ${{ env.SHA }} | sed -n 's#^ *origin/##p' | head -n 1)
+        if [[ -z "$branch" ]]; then
+          echo "Failed to extract branch name for SHA: ${{ env.SHA }}"
+          exit 1
+        fi
+        echo "BRANCH_NAME=$branch" >> $GITHUB_ENV
+
+    - name: Set Environment Name
+      run: |
+        envirn=${{ env.BRANCH_NAME }}" | sed 's/^code-//'
+        echo "ENV_NAME=$envirn >> $GITHUB_ENV
 
     - name: Increment version
       run: |
-        envirn=$(echo "${{ env.BRANCH_NAME }}" | sed 's#code-##') # Note the change here
-        echo "ENVIRN=${envirn}" >> $GITHUB_ENV
         declare -a VERSION=( $MAJOR $MINOR $PATCH )
-        case "${{ env.ENVIRN }}" in
+        case "${{ env.ENV_NAME }}" in
           "development") ((VERSION[2]++)) ;;
           "staging") ((VERSION[1]++)) ;;
           "production") ((VERSION[0]++)) ;;
@@ -45,7 +55,7 @@ jobs:
         PRODUCTION=${VERSION[0]}
         STAGING=${VERSION[1]}
         DEVELOPMENT=${VERSION[2]}
-        echo "NEW_VERSION=v${PRODUCTION}.${STAGING}.${DEVELOPMENT}" >> $GITHUB_ENV
+        echo "NEW_VERSION=${PRODUCTION}.${STAGING}.${DEVELOPMENT}" >> $GITHUB_ENV
 
     - name: Log in to Docker Hub
       uses: docker/login-action@vv2.2.0
@@ -55,10 +65,9 @@ jobs:
 
     - name: Build and push Docker image
       run: |
-        docker_repo="blazor-sqlite-devops"
         docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${docker_repo}:v${{ env.NEW_VERSION }} -f "./${{ env.PROJ_NAME }}/Dockerfile" "./${{ env.PROJ_NAME }}"
-        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${docker_repo}:v${{ env.NEW_VERSION }}
-        echo "Deployed ${{ env.SHA }} from ${{ env.BRANCH_NAME }} for ${{ env.ENVIRN }} to Dockerhub"
+        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPO }}v:${{ env.NEW_VERSION }}
+        echo "Deployed ${{ env.SHA }} from ${{ env.BRANCH_NAME }} for ${{ env.ENV_NAME }} to Dockerhub"
 
     - name: Set new version secret
       uses: hmanzur/actions-set-secret@v2.0.0
@@ -70,4 +79,4 @@ jobs:
 
     - name: Deploy
       if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
-      run: echo "Deployed ${{ env.SHA }} from ${{ env.BRANCH_NAME }} to ${{ env.ENVIRN }} as ${{ env.DOCKER_NAME }}"
+      run: echo "Deployed ${{ env.SHA }} from ${{ env.BRANCH_NAME }} to ${{ env.ENV_NAME }} as ${{ env.DOCKER_NAME }}"
