Update workflow-versioning.yml

diff --git a/.github/workflows/workflow-versioning.yml b/.github/workflows/workflow-versioning.yml
--- a/.github/workflows/workflow-versioning.yml
+++ b/.github/workflows/workflow-versioning.yml
@@ -70,24 +70,31 @@ jobs:
     - name: Check for lock and retry
       run: |
         trap 'echo "Error on line $LINENO: $BASH_COMMAND"; exit 1' ERR
-    
+
         RETRY_COUNT=0
         MAX_RETRIES=3
         SLEEP_DURATION=3600  # 60 minutes in seconds
-    
+
         while true; do
           # Fetch all updates
           git fetch origin ${{ env.BRANCH_NAME }}
-    
+
           # Validate SHA commit
-          git show ${{ github.event.client_payload.sha }}
-    
+          if ! git show ${{ github.event.client_payload.sha }}; then
+              echo "Error: The commit ${{ github.event.client_payload.sha }} does not exist!"
+              exit 1
+          fi
+          
           # Check SHA commit in branch
-          git branch --contains ${{ github.event.client_payload.sha }}
-    
+          branch_contains=$(git branch --contains ${{ github.event.client_payload.sha }})
+          if [ -z "$branch_contains" ]; then
+              echo "Error: No branch contains the commit ${{ github.event.client_payload.sha }}!"
+              exit 1
+          fi
+
           # Fetch the commits that are before the provided SHA and are on the SHA branch
           commits_before_sha=$(git rev-list ${{ github.event.client_payload.sha }}~1..${{ env.BRANCH_NAME }} --)
-          
+
           lock_found=0
           for commit in $commits_before_sha; do
             # Check if the lock file exists in the commit
@@ -96,14 +103,14 @@ jobs:
                 break
             fi
           done
-    
+
           if [[ "$lock_found" -eq 1 ]]; then
             # Check if retry count exceeds max retries
             if [[ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]]; then
               echo "Exceeded maximum retries. Lock file still found. Exiting."
               exit 1
             fi
-    
+
             # Increment retry count and sleep
             RETRY_COUNT=$((RETRY_COUNT+1))
             echo "Lock file found in a commit prior to the payload SHA. Waiting 60 minutes before retrying. Attempt $RETRY_COUNT of $MAX_RETRIES."
@@ -113,12 +120,12 @@ jobs:
             break
           fi
         done
-    
+
         # Create or update the lock file with the current timestamp
         echo "$(date +%s)" > "${{ env.LOCK_FILE }}"
         git add "${{ env.LOCK_FILE }}"
         git commit -m "Add lock for versioning"
-    
+
         # Push the updated lock file to the repository. If push fails, exit.
         if ! git push origin HEAD:${{ env.BRANCH_NAME }}; then
           echo "Failed to push. Exiting."
@@ -147,7 +154,7 @@ jobs:
             major=$(echo "$latest_tag" | cut -d'.' -f1 | tr -dc '0-9')
             minor=$(echo "$latest_tag" | cut -d'.' -f2)
             patch=$(echo "$latest_tag" | cut -d'.' -f3)
-    
+
             # Increment version based on the branch 
             case "${{ env.BRANCH_NAME }}" in
               "code-production")
@@ -169,12 +176,12 @@ jobs:
                 echo "Unknown branch: ${{ env.BRANCH_NAME }}. Retaining current version."
                 ;;
             esac
-    
+
             # Formulate the new version and store it in the environment variable
             new_version="v$major.$minor.$patch"
             echo "Determined new version: $new_version"
             echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
-    
+
         # Create a new tag in the repository with the calculated version
         - name: Tag repository with new version
           run: |
@@ -205,7 +212,7 @@ jobs:
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/dispatches \
                    -d '{ "event_type": "trigger-docker-deploy", "client_payload": { "sha": "${{ github.sha }}" } }')
-      
+
           if [ "$response" -ne 200 ]; then
             echo "Failed to trigger Docker deployment. HTTP response code: $response"
             exit 1
